-- Liga cada canônico ao GIF autorizado (object_key relativo a output/).
-- file_id permanece nulo até o upload no bucket Nhost exercise-media.
-- Sem UNIQUE em object_key: dois nomes podem apontar ao mesmo arquivo.
-- Aplicar depois da migration exercise_media e do seed 003.

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Abdução Lateral do Quadril com Alavanca', 'gifs/gluteos/abducao-lateral-do-quadril-com-alavanca.gif'),
  ('Abdução de Quadril Lateral', 'gifs/funcional-e-hit/abducao-de-quadril-lateral.gif'),
  ('Abdução de Quadril Sentado com Faixa Elástica', 'gifs/funcional-e-hit/abducao-de-quadril-sentado-com-faixa-elastica.gif'),
  ('Abdução de Quadril com Faixa', 'gifs/funcional-e-hit/abducao-de-quadril-com-faixa.gif'),
  ('Abdução de Quadril com Ponte', 'gifs/gluteos/abducao-de-quadril-com-ponte.gif'),
  ('Abdução de Quadril em Decúbito Lateral', 'gifs/funcional-e-hit/abducao-de-quadril-em-decubito-lateral.gif'),
  ('Abdução de Quadril em Pé', 'gifs/funcional-e-hit/abducao-de-quadril-em-pe.gif'),
  ('Abdução de quadril com cabo', 'gifs/gluteos/abducao-de-quadril-com-cabo.gif'),
  ('Abraços nos Joelhos em Pé', 'gifs/mobilidade/abracos-nos-joelhos-em-pe.gif'),
  ('Adução de Ombro com Faixa Elástica', 'gifs/funcional-e-hit/aducao-de-ombro-com-faixa-elastica.gif'),
  ('Adução de quadril deitado de lado', 'gifs/mobilidade/aducao-de-quadril-deitado-de-lado.gif'),
  ('Adução do Quadril Lateral com Alavanca', 'gifs/pernas/aducao-do-quadril-lateral-com-alavanca.gif'),
  ('Adução do Quadril com Cabo', 'gifs/pernas/aducao-do-quadril-com-cabo.gif'),
  ('Afundo', 'gifs/calistenia/afundo.gif'),
  ('Afundo Alternado com Salto', 'gifs/funcional-e-hit/afundo-alternado-com-salto.gif'),
  ('Afundo Lateral', 'gifs/funcional-e-hit/afundo-lateral.gif'),
  ('Afundo Lateral com Barra', 'gifs/pernas/afundo-lateral-com-barra.gif'),
  ('Afundo Profundo', 'gifs/calistenia/afundo-profundo.gif'),
  ('Afundo com Barra', 'gifs/pernas/afundo-com-barra.gif'),
  ('Afundo com Gymstick', 'gifs/funcional-e-hit/afundo-com-gymstick.gif'),
  ('Afundo com Halteres', 'gifs/pernas/afundo-com-halteres.gif'),
  ('Afundo com landmine', 'gifs/pernas/afundo-com-landmine.gif'),
  ('Afundo na Máquina Smith', 'gifs/pernas/afundo-na-maquina-smith.gif'),
  ('Afundo no banco', 'gifs/calistenia/afundo-no-banco.gif'),
  ('Afundo no banco com halteres', 'gifs/pernas/afundo-no-banco-com-halteres.gif'),
  ('Agachamento', 'gifs/calistenia/agachamento.gif'),
  ('Agachamento Barra', 'gifs/pernas/agachamento-barra.gif'),
  ('Agachamento Búlgaro Calistenia', 'gifs/calistenia/agachamento-bulgaro-calistenia.gif'),
  ('Agachamento Búlgaro com Barra', 'gifs/pernas/agachamento-bulgaro-com-barra.gif'),
  ('Agachamento Búlgaro com Halteres', 'gifs/pernas/agachamento-bulgaro-com-halteres.gif'),
  ('Agachamento Búlgaro com Peso Corporal', 'gifs/funcional-e-hit/agachamento-bulgaro-com-peso-corporal.gif'),
  ('Agachamento Camarão', 'gifs/calistenia/agachamento-camarao.gif'),
  ('Agachamento Cossaco', 'gifs/funcional-e-hit/agachamento-cossaco.gif'),
  ('Agachamento Dividido Profundo', 'gifs/funcional-e-hit/agachamento-dividido-profundo.gif'),
  ('Agachamento Frontal', 'gifs/pernas/agachamento-frontal.gif'),
  ('Agachamento Frontal com Barra no Banco', 'gifs/pernas/agachamento-frontal-com-barra-no-banco.gif'),
  ('Agachamento Frontal com Barra no Smith', 'gifs/pernas/agachamento-frontal-com-barra-no-smith.gif'),
  ('Agachamento Frontal com Cabo', 'gifs/pernas/agachamento-frontal-com-cabo.gif'),
  ('Agachamento Frontal com Kettlebell', 'gifs/pernas/agachamento-frontal-com-kettlebell.gif'),
  ('Agachamento Frontal com Polia', 'gifs/pernas/agachamento-frontal-com-polia.gif'),
  ('Agachamento Funcional', 'gifs/funcional-e-hit/agachamento-funcional.gif'),
  ('Agachamento Goblet com Haltere', 'gifs/pernas/agachamento-goblet-com-haltere.gif'),
  ('Agachamento Goblet com Kettlebell e Faixa Elástica', 'gifs/funcional-e-hit/agachamento-goblet-com-kettlebell-e-faixa-elastica.gif'),
  ('Agachamento Hack Invertido', 'gifs/pernas/agachamento-hack-invertido.gif'),
  ('Agachamento Jefferson', 'gifs/pernas/agachamento-jefferson.gif'),
  ('Agachamento Pistol com TRX', 'gifs/calistenia/agachamento-pistol-com-trx.gif'),
  ('Agachamento Pistola Apoiado', 'gifs/calistenia/agachamento-pistola-apoiado.gif'),
  ('Agachamento Pistola com Apoio em Caixa', 'gifs/crossfit/agachamento-pistola-com-apoio-em-caixa.gif'),
  ('Agachamento Pistola com Halteres', 'gifs/crossfit/agachamento-pistola-com-halteres.gif'),
  ('Agachamento Pistola com Kettlebell', 'gifs/calistenia/agachamento-pistola-com-kettlebell.gif'),
  ('Agachamento Pistola na Caixa', 'gifs/calistenia/agachamento-pistola-na-caixa.gif'),
  ('Agachamento Sissy', 'gifs/pernas/agachamento-sissy.gif'),
  ('Agachamento Sissy ajoelhado com Peso Corporal', 'gifs/calistenia/agachamento-sissy-ajoelhado-com-peso-corporal.gif'),
  ('Agachamento Skater', 'gifs/calistenia/agachamento-skater.gif'),
  ('Agachamento Sumô com Halteres', 'gifs/pernas/agachamento-sumo-com-halteres.gif'),
  ('Agachamento Sumô sem Pesos', 'gifs/calistenia/agachamento-sumo-sem-pesos.gif'),
  ('Agachamento Zercher', 'gifs/pernas/agachamento-zercher.gif'),
  ('Agachamento búlgaro com salto', 'gifs/calistenia/agachamento-bulgaro-com-salto.gif'),
  ('Agachamento com Barra Sobre a Cabeça', 'gifs/crossfit/agachamento-com-barra-sobre-a-cabeca.gif'),
  ('Agachamento com Chute Lateral e Toque no Calcanhar', 'gifs/funcional-e-hit/agachamento-com-chute-lateral-e-toque-no-calcanhar.gif'),
  ('Agachamento com Cinto', 'gifs/pernas/agachamento-com-cinto.gif'),
  ('Agachamento com Elevação dos Joelhos', 'gifs/funcional-e-hit/agachamento-com-elevacao-dos-joelhos.gif'),
  ('Agachamento com Faixa Elástica em Afundo', 'gifs/funcional-e-hit/agachamento-com-faixa-elastica-em-afundo.gif'),
  ('Agachamento com Faixa Elástica sobre a Cabeça', 'gifs/funcional-e-hit/agachamento-com-faixa-elastica-sobre-a-cabeca.gif'),
  ('Agachamento com Gymstick', 'gifs/funcional-e-hit/agachamento-com-gymstick.gif'),
  ('Agachamento com Halteres no Banco', 'gifs/pernas/agachamento-com-halteres-no-banco.gif'),
  ('Agachamento com Joelho Elevado', 'gifs/calistenia/agachamento-com-joelho-elevado.gif'),
  ('Agachamento com Salto', 'gifs/calistenia/agachamento-com-salto.gif'),
  ('Agachamento com Salto usando Barra Hexagonal', 'gifs/crossfit/agachamento-com-salto-usando-barra-hexagonal.gif'),
  ('Agachamento com Sustentação e Elevação de Panturrilhas', 'gifs/calistenia/agachamento-com-sustentacao-e-elevacao-de-panturrilhas.gif'),
  ('Agachamento com Trava', 'gifs/pernas/agachamento-com-trava.gif'),
  ('Agachamento com barra e salto', 'gifs/crossfit/agachamento-com-barra-e-salto.gif'),
  ('Agachamento com barra no chão seguido de levantamento militar', 'gifs/crossfit/agachamento-com-barra-no-chao-seguido-de-levantamento-militar.gif'),
  ('Agachamento com kettlebell', 'gifs/pernas/agachamento-com-kettlebell.gif'),
  ('Agachamento com salto ajoelhado', 'gifs/crossfit/agachamento-com-salto-ajoelhado.gif'),
  ('Agachamento com salto e halteres', 'gifs/pernas/agachamento-com-salto-e-halteres.gif'),
  ('Agachamento e press com kettlebell', 'gifs/crossfit/agachamento-e-press-com-kettlebell.gif'),
  ('Agachamento em plié com halteres', 'gifs/pernas/agachamento-em-plie-com-halteres.gif'),
  ('Agachamento hack com barra', 'gifs/pernas/agachamento-hack-com-barra.gif'),
  ('Agachamento havaiano', 'gifs/calistenia/agachamento-havaiano.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Agachamento na Máquina Abdutora', 'gifs/gluteos/agachamento-na-maquina-abdutora.gif'),
  ('Agachamento na Máquina Hack', 'gifs/pernas/agachamento-na-maquina-hack.gif'),
  ('Agachamento na Parede com Bola de Exercício', 'gifs/funcional-e-hit/agachamento-na-parede-com-bola-de-exercicio.gif'),
  ('Agachamento no Banco com Peso Corporal', 'gifs/calistenia/agachamento-no-banco-com-peso-corporal.gif'),
  ('Agachamento no Landmine', 'gifs/pernas/agachamento-no-landmine.gif'),
  ('Agachamento no Smith', 'gifs/pernas/agachamento-no-smith.gif'),
  ('Agachamento pistola', 'gifs/calistenia/agachamento-pistola.gif'),
  ('Agachamento unilateral cruzado', 'gifs/funcional-e-hit/agachamento-unilateral-cruzado.gif'),
  ('Agachamento unilateral cruzado com Barra', 'gifs/pernas/agachamento-unilateral-cruzado-com-barra.gif'),
  ('Agachamento unilateral cruzado com haltere', 'gifs/pernas/agachamento-unilateral-cruzado-com-haltere.gif'),
  ('Airbike', 'gifs/cardio/airbike.gif'),
  ('Alongamento Abraço com Tapinhas nas Costas', 'gifs/mobilidade/alongamento-abraco-com-tapinhas-nas-costas.gif'),
  ('Alongamento Borboleta', 'gifs/mobilidade/alongamento-borboleta.gif'),
  ('Alongamento Dinâmico do Peitoral', 'gifs/mobilidade/alongamento-dinamico-do-peitoral.gif'),
  ('Alongamento Inclinado Lateral em Pé', 'gifs/mobilidade/alongamento-inclinado-lateral-em-pe.gif'),
  ('Alongamento Lateral da Parte Interna da Coxa', 'gifs/mobilidade/alongamento-lateral-da-parte-interna-da-coxa.gif'),
  ('Alongamento Piriforme', 'gifs/mobilidade/alongamento-piriforme.gif'),
  ('Alongamento Reverso de Pulso', 'gifs/mobilidade/alongamento-reverso-de-pulso.gif'),
  ('Alongamento Sentado para a Panturrilha com Perna Esticada', 'gifs/mobilidade/alongamento-sentado-para-a-panturrilha-com-perna-esticada.gif'),
  ('Alongamento assistido reverso (peitoral e ombro)', 'gifs/mobilidade/alongamento-assistido-reverso-peitoral-e-ombro.gif'),
  ('Alongamento com PVC na Posição Frontal de Rack', 'gifs/mobilidade/alongamento-com-pvc-na-posicao-frontal-de-rack.gif'),
  ('Alongamento da Esfinge', 'gifs/mobilidade/alongamento-da-esfinge.gif'),
  ('Alongamento da panturrilha agachado', 'gifs/mobilidade/alongamento-da-panturrilha-agachado.gif'),
  ('Alongamento da panturrilha com descida do calcanhar', 'gifs/mobilidade/alongamento-da-panturrilha-com-descida-do-calcanhar.gif'),
  ('Alongamento da parte superior das costas', 'gifs/mobilidade/alongamento-da-parte-superior-das-costas.gif'),
  ('Alongamento das Costas com Rolo de Espuma', 'gifs/mobilidade/alongamento-das-costas-com-rolo-de-espuma.gif'),
  ('Alongamento de Adutores com Pernas Afastadas em Pé', 'gifs/mobilidade/alongamento-de-adutores-com-pernas-afastadas-em-pe.gif'),
  ('Alongamento de Glúteos Deitado', 'gifs/mobilidade/alongamento-de-gluteos-deitado.gif'),
  ('Alongamento de Isquiotibiais deitado', 'gifs/mobilidade/alongamento-de-isquiotibiais-deitado.gif'),
  ('Alongamento de Isquiotibiais em Pé', 'gifs/mobilidade/alongamento-de-isquiotibiais-em-pe.gif'),
  ('Alongamento de Panturrilha com Corda', 'gifs/mobilidade/alongamento-de-panturrilha-com-corda.gif'),
  ('Alongamento de Pernas Duplo', 'gifs/mobilidade/alongamento-de-pernas-duplo.gif'),
  ('Alongamento de Punho', 'gifs/mobilidade/alongamento-de-punho.gif'),
  ('Alongamento de Quadríceps ajoelhado', 'gifs/mobilidade/alongamento-de-quadriceps-ajoelhado.gif'),
  ('Alongamento de Quadríceps em Quatro Apoios', 'gifs/mobilidade/alongamento-de-quadriceps-em-quatro-apoios.gif'),
  ('Alongamento de ombro com o braço cruzado', 'gifs/mobilidade/alongamento-de-ombro-com-o-braco-cruzado.gif'),
  ('Alongamento de ombro reverso em pé', 'gifs/mobilidade/alongamento-de-ombro-reverso-em-pe.gif'),
  ('Alongamento de panturrilha com uma perna', 'gifs/mobilidade/alongamento-de-panturrilha-com-uma-perna.gif'),
  ('Alongamento de panturrilha com uma perna esticada', 'gifs/mobilidade/alongamento-de-panturrilha-com-uma-perna-esticada.gif'),
  ('Alongamento de panturrilha em passo largo', 'gifs/mobilidade/alongamento-de-panturrilha-em-passo-largo.gif'),
  ('Alongamento de panturrilha em posição estática', 'gifs/mobilidade/alongamento-de-panturrilha-em-posicao-estatica.gif'),
  ('Alongamento de panturrilha na parede', 'gifs/mobilidade/alongamento-de-panturrilha-na-parede.gif'),
  ('Alongamento de quadril 90-90', 'gifs/mobilidade/alongamento-de-quadril-90-90.gif'),
  ('Alongamento de rotação da coluna em pé', 'gifs/mobilidade/alongamento-de-rotacao-da-coluna-em-pe.gif'),
  ('Alongamento de tríceps em pé', 'gifs/mobilidade/alongamento-de-triceps-em-pe.gif'),
  ('Alongamento do Gastrocnêmio com Joelho Flexionado', 'gifs/mobilidade/alongamento-do-gastrocnemio-com-joelho-flexionado.gif'),
  ('Alongamento do Peito Acima da Cabeça', 'gifs/mobilidade/alongamento-do-peito-acima-da-cabeca.gif'),
  ('Alongamento do Peito e Parte Frontal dos Ombros', 'gifs/mobilidade/alongamento-do-peito-e-parte-frontal-dos-ombros.gif'),
  ('Alongamento do Peitoral até as Costas', 'gifs/mobilidade/alongamento-do-peitoral-ate-as-costas.gif'),
  ('Alongamento do Peitoral com um Braço em Pé', 'gifs/mobilidade/alongamento-do-peitoral-com-um-braco-em-pe.gif'),
  ('Alongamento do Piriforme Sentado', 'gifs/mobilidade/alongamento-do-piriforme-sentado.gif'),
  ('Alongamento do desviador ulnar e extensor do punho', 'gifs/mobilidade/alongamento-do-desviador-ulnar-e-extensor-do-punho.gif'),
  ('Alongamento do manguito rotador', 'gifs/mobilidade/alongamento-do-manguito-rotador.gif'),
  ('Alongamento do ombro com toalha', 'gifs/mobilidade/alongamento-do-ombro-com-toalha.gif'),
  ('Alongamento do peito com rolo de espuma', 'gifs/mobilidade/alongamento-do-peito-com-rolo-de-espuma.gif'),
  ('Alongamento do peitoral e do ombro na porta', 'gifs/mobilidade/alongamento-do-peitoral-e-do-ombro-na-porta.gif'),
  ('Alongamento do peitoral reverso', 'gifs/calistenia/alongamento-do-peitoral-reverso.gif'),
  ('Alongamento do tendão de Aquiles em pé', 'gifs/mobilidade/alongamento-do-tendao-de-aquiles-em-pe.gif'),
  ('Alongamento do tibial posterior', 'gifs/mobilidade/alongamento-do-tibial-posterior.gif'),
  ('Alongamento do trato iliotibial com rolo de espuma', 'gifs/mobilidade/alongamento-do-trato-iliotibial-com-rolo-de-espuma.gif'),
  ('Alongamento dos Adutores com Pernas Abertas em Pé', 'gifs/mobilidade/alongamento-dos-adutores-com-pernas-abertas-em-pe.gif'),
  ('Alongamento dos Adutores com a Perna Estendida ajoelhado', 'gifs/mobilidade/alongamento-dos-adutores-com-a-perna-estendida-ajoelhado.gif'),
  ('Alongamento dos Adutores em Posição Sentada com Pernas Abertas', 'gifs/mobilidade/alongamento-dos-adutores-em-posicao-sentada-com-pernas-abertas.gif'),
  ('Alongamento dos Extensores dos Dedos dos Pés', 'gifs/mobilidade/alongamento-dos-extensores-dos-dedos-dos-pes.gif'),
  ('Alongamento dos Isquiotibiais Sentado', 'gifs/mobilidade/alongamento-dos-isquiotibiais-sentado.gif'),
  ('Alongamento dos adutores da coxa com rolo de espuma', 'gifs/mobilidade/alongamento-dos-adutores-da-coxa-com-rolo-de-espuma.gif'),
  ('Alongamento dos adutores sentado', 'gifs/mobilidade/alongamento-dos-adutores-sentado.gif'),
  ('Alongamento dos flexores de quadril ajoelhado', 'gifs/mobilidade/alongamento-dos-flexores-de-quadril-ajoelhado.gif'),
  ('Alongamento dos flexores do quadril em posição de joelho', 'gifs/mobilidade/alongamento-dos-flexores-do-quadril-em-posicao-de-joelho.gif'),
  ('Alongamento dos flexores dos dedos dos pés em pé', 'gifs/mobilidade/alongamento-dos-flexores-dos-dedos-dos-pes-em-pe.gif'),
  ('Alongamento dos isquiotibiais em pé', 'gifs/mobilidade/alongamento-dos-isquiotibiais-em-pe.gif'),
  ('Alongamento dos isquiotibiais em pé com a perna cruzada', 'gifs/mobilidade/alongamento-dos-isquiotibiais-em-pe-com-a-perna-cruzada.gif'),
  ('Alongamento dos latíssimos dorsais com rolo de espuma', 'gifs/mobilidade/alongamento-dos-latissimos-dorsais-com-rolo-de-espuma.gif'),
  ('Alongamento dos ombros por trás das costas', 'gifs/mobilidade/alongamento-dos-ombros-por-tras-das-costas.gif'),
  ('Alongamento em Círculos nos Punhos', 'gifs/mobilidade/alongamento-em-circulos-nos-punhos.gif'),
  ('Alongamento em Pé dos Quadríceps', 'gifs/mobilidade/alongamento-em-pe-dos-quadriceps.gif'),
  ('Alongamento na parede do canto', 'gifs/mobilidade/alongamento-na-parede-do-canto.gif'),
  ('Alongamento reverso assistido (peito e ombro)', 'gifs/mobilidade/alongamento-reverso-assistido-peito-e-ombro.gif'),
  ('Alongamentos de pés e tornozelos', 'gifs/mobilidade/alongamentos-de-pes-e-tornozelos.gif'),
  ('Andar de Bicicleta ao Ar Livre', 'gifs/funcional-e-hit/andar-de-bicicleta-ao-ar-livre.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Andar de Pato', 'gifs/calistenia/andar-de-pato.gif'),
  ('Anilha Press', 'gifs/peitoral/anilha-press.gif'),
  ('Arranco com Barra', 'gifs/crossfit/arranco-com-barra.gif'),
  ('Arranco com kettlebell de um braço', 'gifs/crossfit/arranco-com-kettlebell-de-um-braco.gif'),
  ('Arranco com kettlebell em afundo', 'gifs/crossfit/arranco-com-kettlebell-em-afundo.gif'),
  ('Arranco de Potência', 'gifs/crossfit/arranco-de-potencia.gif'),
  ('Arranco e Levantamento com Kettlebell', 'gifs/crossfit/arranco-e-levantamento-com-kettlebell.gif'),
  ('Arranque e Arremesso com Kettlebell', 'gifs/crossfit/arranque-e-arremesso-com-kettlebell.gif'),
  ('Arremesso com Barra', 'gifs/crossfit/arremesso-com-barra.gif'),
  ('Arremesso com haltere de um braço', 'gifs/crossfit/arremesso-com-haltere-de-um-braco.gif'),
  ('Arremesso de Bola de Reação', 'gifs/funcional-e-hit/arremesso-de-bola-de-reacao.gif'),
  ('Arremesso de Medicina Bola com Levantamento de Tronco', 'gifs/crossfit/arremesso-de-medicina-bola-com-levantamento-de-tronco.gif'),
  ('Arremesso e Pressão com Barra', 'gifs/crossfit/arremesso-e-pressao-com-barra.gif'),
  ('Avanço Invertido', 'gifs/pernas/avanco-invertido.gif'),
  ('Avanço Invertido com Halteres', 'gifs/pernas/avanco-invertido-com-halteres.gif'),
  ('Avanço com Barra', 'gifs/pernas/avanco-com-barra.gif'),
  ('Avanço com Cabo', 'gifs/pernas/avanco-com-cabo.gif'),
  ('Avanço com Halteres', 'gifs/pernas/avanco-com-halteres.gif'),
  ('Avanço com Halteres para Trás', 'gifs/pernas/avanco-com-halteres-para-tras.gif'),
  ('Avanço com Joelho Alto em Cima da Bola Bosu', 'gifs/funcional-e-hit/avanco-com-joelho-alto-em-cima-da-bola-bosu.gif'),
  ('Avanço com Joelho Elevado em Caminhada', 'gifs/funcional-e-hit/avanco-com-joelho-elevado-em-caminhada.gif'),
  ('Avanço com Puxador de Cabo', 'gifs/pernas/avanco-com-puxador-de-cabo.gif'),
  ('Avanço sem Peso Corporal', 'gifs/calistenia/avanco-sem-peso-corporal.gif'),
  ('Back Lever', 'gifs/calistenia/back-lever.gif'),
  ('Balanço com gymstick', 'gifs/funcional-e-hit/balanco-com-gymstick.gif'),
  ('Balanços com Kettlebell', 'gifs/crossfit/balancos-com-kettlebell.gif'),
  ('Balloon Drill', 'gifs/funcional-e-hit/balloon-drill.gif'),
  ('Bandeira Humana', 'gifs/calistenia/bandeira-humana.gif'),
  ('Barbell Hang Clean', 'gifs/crossfit/barbell-hang-clean.gif'),
  ('Barra Fixa Assistida', 'gifs/costas/barra-fixa-assistida.gif'),
  ('Barra Fixa com Giro', 'gifs/calistenia/barra-fixa-com-giro.gif'),
  ('Barra Fixa com Pegada Fechada', 'gifs/calistenia/barra-fixa-com-pegada-fechada.gif'),
  ('Barra Fixa com Pegada Supinada', 'gifs/calistenia/barra-fixa-com-pegada-supinada.gif'),
  ('Barra Fixa com Pegada por Trás do Pescoço', 'gifs/calistenia/barra-fixa-com-pegada-por-tras-do-pescoco.gif'),
  ('Barra Fixa de Cabeça para Baixo', 'gifs/calistenia/barra-fixa-de-cabeca-para-baixo.gif'),
  ('Barra Fixa para o Braquial', 'gifs/calistenia/barra-fixa-para-o-braquial.gif'),
  ('Barra fixa', 'gifs/costas/barra-fixa.gif'),
  ('Barra fixa Assistida com Faixa Elástica', 'gifs/calistenia/barra-fixa-assistida-com-faixa-elastica.gif'),
  ('Barra fixa com Arco', 'gifs/calistenia/barra-fixa-com-arco.gif'),
  ('Barra fixa com L-sit', 'gifs/calistenia/barra-fixa-com-l-sit.gif'),
  ('Barra fixa com Salto', 'gifs/calistenia/barra-fixa-com-salto.gif'),
  ('Barra fixa com braços alternados', 'gifs/calistenia/barra-fixa-com-bracos-alternados.gif'),
  ('Barra fixa com pegada invertida assistido', 'gifs/calistenia/barra-fixa-com-pegada-invertida-assistido.gif'),
  ('Barra fixa com pegada neutra', 'gifs/calistenia/barra-fixa-com-pegada-neutra.gif'),
  ('Barra fixa com peso', 'gifs/calistenia/barra-fixa-com-peso.gif'),
  ('Barra fixa pegada invertida', 'gifs/calistenia/barra-fixa-pegada-invertida.gif'),
  ('Bicicleta Ergométrica Reclinada', 'gifs/cardio/bicicleta-ergometrica-reclinada.gif'),
  ('Bike', 'gifs/cardio/bike.gif'),
  ('Bola medicinal lançada para cima e para baixo', 'gifs/crossfit/bola-medicinal-lancada-para-cima-e-para-baixo.gif'),
  ('Bola na parede', 'gifs/crossfit/bola-na-parede.gif'),
  ('Bom Dia com Faixa Elástica de Resistência', 'gifs/funcional-e-hit/bom-dia-com-faixa-elastica-de-resistencia.gif'),
  ('Bom Dia na Máquina Smith', 'gifs/pernas/bom-dia-na-maquina-smith.gif'),
  ('Bom dia', 'gifs/pernas/bom-dia.gif'),
  ('Bom dia (1)', 'gifs/pernas/bom-dia-1.gif'),
  ('Boxe Sombra', 'gifs/funcional-e-hit/boxe-sombra.gif'),
  ('Boxe jab', 'gifs/funcional-e-hit/boxe-jab.gif'),
  ('Burpee Jack', 'gifs/crossfit/burpee-jack.gif'),
  ('Burpees', 'gifs/crossfit/burpees.gif'),
  ('Cadeira extensora', 'gifs/pernas/cadeira-extensora.gif'),
  ('Cadeira flexora', 'gifs/pernas/cadeira-flexora.gif'),
  ('Caminhada Lateral com Faixa de Resistência', 'gifs/funcional-e-hit/caminhada-lateral-com-faixa-de-resistencia.gif'),
  ('Caminhada Rápida', 'gifs/funcional-e-hit/caminhada-rapida.gif'),
  ('Caminhada com Halteres', 'gifs/crossfit/caminhada-com-halteres.gif'),
  ('Caminhada na Parada de Mão', 'gifs/calistenia/caminhada-na-parada-de-mao.gif'),
  ('Caminhada na Parede', 'gifs/crossfit/caminhada-na-parede.gif'),
  ('Caminhar', 'gifs/funcional-e-hit/caminhar.gif'),
  ('Cardio de Passos de Boxeador', 'gifs/funcional-e-hit/cardio-de-passos-de-boxeador.gif'),
  ('Carregamento Zercher', 'gifs/crossfit/carregamento-zercher.gif'),
  ('Catavento corporal', 'gifs/mobilidade/catavento-corporal.gif'),
  ('Chute em Gancho', 'gifs/funcional-e-hit/chute-em-gancho.gif'),
  ('Chutes Alternados de Glúteos no Banco', 'gifs/funcional-e-hit/chutes-alternados-de-gluteos-no-banco.gif'),
  ('Chutes até o Glúteo', 'gifs/funcional-e-hit/chutes-ate-o-gluteo.gif'),
  ('Coice com Perna Flexionada', 'gifs/funcional-e-hit/coice-com-perna-flexionada.gif'),
  ('Coice de Burro', 'gifs/funcional-e-hit/coice-de-burro.gif'),
  ('Contração abdominal', 'gifs/mobilidade/contracao-abdominal.gif'),
  ('Corda de batalha', 'gifs/crossfit/corda-de-batalha.gif'),
  ('Corrida', 'gifs/funcional-e-hit/corrida.gif'),
  ('Corrida Estacionária', 'gifs/funcional-e-hit/corrida-estacionaria.gif'),
  ('Corrida Latera', 'gifs/funcional-e-hit/corrida-latera.gif'),
  ('Corrida com Elevação dos Joelhos', 'gifs/funcional-e-hit/corrida-com-elevacao-dos-joelhos.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Corrida com Joelhos Altos', 'gifs/funcional-e-hit/corrida-com-joelhos-altos.gif'),
  ('Corrida com Passos Rápidos', 'gifs/funcional-e-hit/corrida-com-passos-rapidos.gif'),
  ('Corrida com Salto', 'gifs/funcional-e-hit/corrida-com-salto.gif'),
  ('Corrida de Passos Curtos', 'gifs/funcional-e-hit/corrida-de-passos-curtos.gif'),
  ('Corrida de Sprint com Assistência de Faixa Elástica', 'gifs/funcional-e-hit/corrida-de-sprint-com-assistencia-de-faixa-elastica.gif'),
  ('Corrida na Bicicleta Ergométrica', 'gifs/cardio/corrida-na-bicicleta-ergometrica.gif'),
  ('Corrida para Trás', 'gifs/funcional-e-hit/corrida-para-tras.gif'),
  ('Cross over polia Alta', 'gifs/peitoral/cross-over-polia-alta.gif'),
  ('Cross over polia baixa', 'gifs/peitoral/cross-over-polia-baixa.gif'),
  ('Cross over polia media', 'gifs/peitoral/cross-over-polia-media.gif'),
  ('Crossover Unilateral com Cabo', 'gifs/peitoral/crossover-unilateral-com-cabo.gif'),
  ('Crossover de peitoral superior com cabo', 'gifs/peitoral/crossover-de-peitoral-superior-com-cabo.gif'),
  ('Crossover na Alavanca', 'gifs/peitoral/crossover-na-alavanca.gif'),
  ('Crucifixo Deitado com Cabo', 'gifs/peitoral/crucifixo-deitado-com-cabo.gif'),
  ('Crucifixo Inclinado Cross', 'gifs/peitoral/crucifixo-inclinado-cross.gif'),
  ('Crucifixo Unilateral em Declinado com Cabo', 'gifs/peitoral/crucifixo-unilateral-em-declinado-com-cabo.gif'),
  ('Crucifixo com Cabo Declinado', 'gifs/peitoral/crucifixo-com-cabo-declinado.gif'),
  ('Crucifixo com Halteres Declinado', 'gifs/peitoral/crucifixo-com-halteres-declinado.gif'),
  ('Crucifixo com Halteres Inclinado', 'gifs/peitoral/crucifixo-com-halteres-inclinado.gif'),
  ('Crucifixo com TRX', 'gifs/calistenia/crucifixo-com-trx.gif'),
  ('Crucifixo com halteres', 'gifs/peitoral/crucifixo-com-halteres.gif'),
  ('Crucifixo inverso unilateral com cabo', 'gifs/ombros/crucifixo-inverso-unilateral-com-cabo.gif'),
  ('Crucifixo invertido com gymstick para deltoides posterior', 'gifs/funcional-e-hit/crucifixo-invertido-com-gymstick-para-deltoides-posterior.gif'),
  ('Cruz de ferro com halteres', 'gifs/crossfit/cruz-de-ferro-com-halteres.gif'),
  ('Cruzado de Direita', 'gifs/funcional-e-hit/cruzado-de-direita.gif'),
  ('Círculos com os braços', 'gifs/mobilidade/circulos-com-os-bracos.gif'),
  ('Círculos com um braço', 'gifs/mobilidade/circulos-com-um-braco.gif'),
  ('Círculos de Braço com Pesos', 'gifs/ombros/circulos-de-braco-com-pesos.gif'),
  ('Cópia de Abdominal de Rã com Bola de Exercícios', 'gifs/funcional-e-hit/copia-de-abdominal-de-ra-com-bola-de-exercicios.gif'),
  ('Descida de um Pé Só', 'gifs/pernas/descida-de-um-pe-so.gif'),
  ('Desenvolvimento Arnold', 'gifs/ombros/desenvolvimento-arnold.gif'),
  ('Desenvolvimento Arnold (metade)', 'gifs/ombros/desenvolvimento-arnold-metade.gif'),
  ('Desenvolvimento Arnold com kettlebell', 'gifs/crossfit/desenvolvimento-arnold-com-kettlebell.gif'),
  ('Desenvolvimento Cubano com Halteres', 'gifs/ombros/desenvolvimento-cubano-com-halteres.gif'),
  ('Desenvolvimento arnold com um braço', 'gifs/ombros/desenvolvimento-arnold-com-um-braco.gif'),
  ('Desenvolvimento cubano sentado com halteres', 'gifs/ombros/desenvolvimento-cubano-sentado-com-halteres.gif'),
  ('Desenvolvimento de Ombro Alternada em Pé com Halteres', 'gifs/ombros/desenvolvimento-de-ombro-alternada-em-pe-com-halteres.gif'),
  ('Desenvolvimento de Ombro no Banco com Halteres', 'gifs/ombros/desenvolvimento-de-ombro-no-banco-com-halteres.gif'),
  ('Desenvolvimento de Ombros com Rotação Alternada com Halteres', 'gifs/ombros/desenvolvimento-de-ombros-com-rotacao-alternada-com-halteres.gif'),
  ('Desenvolvimento de ombro com barra sentado', 'gifs/ombros/desenvolvimento-de-ombro-com-barra-sentado.gif'),
  ('Desenvolvimento de ombro com cabo', 'gifs/ombros/desenvolvimento-de-ombro-com-cabo.gif'),
  ('Desenvolvimento de ombro com cabo ajoelhado', 'gifs/ombros/desenvolvimento-de-ombro-com-cabo-ajoelhado.gif'),
  ('Desenvolvimento de ombro com halteres em Z', 'gifs/ombros/desenvolvimento-de-ombro-com-halteres-em-z.gif'),
  ('Desenvolvimento de ombro com halteres em forma de W', 'gifs/ombros/desenvolvimento-de-ombro-com-halteres-em-forma-de-w.gif'),
  ('Desenvolvimento de ombro com kettlebell', 'gifs/crossfit/desenvolvimento-de-ombro-com-kettlebell.gif'),
  ('Desenvolvimento de ombro deitado', 'gifs/ombros/desenvolvimento-de-ombro-deitado.gif'),
  ('Desenvolvimento de ombro na máquina', 'gifs/ombros/desenvolvimento-de-ombro-na-maquina.gif'),
  ('Desenvolvimento de ombro na máquina (pegada martelo)', 'gifs/ombros/desenvolvimento-de-ombro-na-maquina-pegada-martelo.gif'),
  ('Desenvolvimento de ombro reversa na máquina', 'gifs/ombros/desenvolvimento-de-ombro-reversa-na-maquina.gif'),
  ('Desenvolvimento de ombro sentado com faixa de resistência', 'gifs/funcional-e-hit/desenvolvimento-de-ombro-sentado-com-faixa-de-resistencia.gif'),
  ('Desenvolvimento de ombro unilateral com banda', 'gifs/funcional-e-hit/desenvolvimento-de-ombro-unilateral-com-banda.gif'),
  ('Desenvolvimento de ombro unilateral com halter', 'gifs/ombros/desenvolvimento-de-ombro-unilateral-com-halter.gif'),
  ('Desenvolvimento de ombros atrás da cabeça na máquina Smith', 'gifs/ombros/desenvolvimento-de-ombros-atras-da-cabeca-na-maquina-smith.gif'),
  ('Desenvolvimento de ombros atrás do pescoço sentado', 'gifs/ombros/desenvolvimento-de-ombros-atras-do-pescoco-sentado.gif'),
  ('Desenvolvimento de ombros com barra W com pegada invertida', 'gifs/ombros/desenvolvimento-de-ombros-com-barra-w-com-pegada-invertida.gif'),
  ('Desenvolvimento de ombros com halteres em pé com pegada neutra', 'gifs/ombros/desenvolvimento-de-ombros-com-halteres-em-pe-com-pegada-neutra.gif'),
  ('Desenvolvimento de ombros na máquina', 'gifs/ombros/desenvolvimento-de-ombros-na-maquina.gif'),
  ('Desenvolvimento de ombros na máquina Smith', 'gifs/ombros/desenvolvimento-de-ombros-na-maquina-smith.gif'),
  ('Desenvolvimento lateral com gymstick', 'gifs/funcional-e-hit/desenvolvimento-lateral-com-gymstick.gif'),
  ('Desenvolvimento militar atrás da cabeça com gymstick', 'gifs/funcional-e-hit/desenvolvimento-militar-atras-da-cabeca-com-gymstick.gif'),
  ('Desenvolvimento militar com barra', 'gifs/ombros/desenvolvimento-militar-com-barra.gif'),
  ('Desenvolvimento militar com barra no chão ajoelhado', 'gifs/ombros/desenvolvimento-militar-com-barra-no-chao-ajoelhado.gif'),
  ('Desenvolvimento militar com pegada fechada', 'gifs/ombros/desenvolvimento-militar-com-pegada-fechada.gif'),
  ('Desenvolvimento militar com peso do corpo', 'gifs/funcional-e-hit/desenvolvimento-militar-com-peso-do-corpo.gif'),
  ('Desenvolvimento militar de uma mão com kettlebell', 'gifs/ombros/desenvolvimento-militar-de-uma-mao-com-kettlebell.gif'),
  ('Desenvolvimento militar em pé na máquina Smith', 'gifs/ombros/desenvolvimento-militar-em-pe-na-maquina-smith.gif'),
  ('Desenvolvimento militar inclinado com barra presa no chão', 'gifs/ombros/desenvolvimento-militar-inclinado-com-barra-presa-no-chao.gif'),
  ('Desenvolvimentos com kettlebell unilateral de joelhos', 'gifs/crossfit/desenvolvimentos-com-kettlebell-unilateral-de-joelhos.gif'),
  ('Deslize de parede do serrátil com rolo de espuma', 'gifs/mobilidade/deslize-de-parede-do-serratil-com-rolo-de-espuma.gif'),
  ('Dips de escápula', 'gifs/trapezio/dips-de-escapula.gif'),
  ('Dips na cadeira', 'gifs/calistenia/dips-na-cadeira.gif'),
  ('Dorsiflexão plantar', 'gifs/mobilidade/dorsiflexao-plantar.gif'),
  ('Dumbbell Devil Press', 'gifs/crossfit/dumbbell-devil-press.gif'),
  ('Dumbbell Power Clean', 'gifs/crossfit/dumbbell-power-clean.gif'),
  ('Dumbbell-Raise', 'gifs/trapezio/dumbbell-raise.gif'),
  ('Elevação Frontal Alternada Com Halteres', 'gifs/ombros/elevacao-frontal-alternada-com-halteres.gif'),
  ('Elevação Lateral de Perna com Faixa Elástica', 'gifs/funcional-e-hit/elevacao-lateral-de-perna-com-faixa-elastica.gif'),
  ('Elevação Lateral de Perna com Faixa Elástica Deitado de Lado', 'gifs/funcional-e-hit/elevacao-lateral-de-perna-com-faixa-elastica-deitado-de-lado.gif'),
  ('Elevação Posterior unilateral com halteres em Decúbito Prono', 'gifs/ombros/elevacao-posterior-unilateral-com-halteres-em-decubito-prono.gif'),
  ('Elevação Pélvica Com Barra', 'gifs/gluteos/elevacao-pelvica-com-barra.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Elevação Pélvica Com Barra Declinado', 'gifs/gluteos/elevacao-pelvica-com-barra-declinado.gif'),
  ('Elevação Pélvica Declinado', 'gifs/calistenia/elevacao-pelvica-declinado.gif'),
  ('Elevação Pélvica Na Máquina', 'gifs/gluteos/elevacao-pelvica-na-maquina.gif'),
  ('Elevação Pélvica Unilateral Com Barra', 'gifs/gluteos/elevacao-pelvica-unilateral-com-barra.gif'),
  ('Elevação Pélvica com Banda de Resistência', 'gifs/funcional-e-hit/elevacao-pelvica-com-banda-de-resistencia.gif'),
  ('Elevação Pélvica na Máquina Smith', 'gifs/gluteos/elevacao-pelvica-na-maquina-smith.gif'),
  ('Elevação Pélvica na Máquina de Extensão de Pernas', 'gifs/gluteos/elevacao-pelvica-na-maquina-de-extensao-de-pernas.gif'),
  ('Elevação Unilateral de Panturrilha no Leg Press', 'gifs/panturrilhas/elevacao-unilateral-de-panturrilha-no-leg-press.gif'),
  ('Elevação com Barra em Degrau', 'gifs/pernas/elevacao-com-barra-em-degrau.gif'),
  ('Elevação com Giro do Cotovelo Oposto para o Joelho', 'gifs/funcional-e-hit/elevacao-com-giro-do-cotovelo-oposto-para-o-joelho.gif'),
  ('Elevação da Perna em Pé com Faixa Elástica de Resistência', 'gifs/funcional-e-hit/elevacao-da-perna-em-pe-com-faixa-elastica-de-resistencia.gif'),
  ('Elevação de Deltoide Posterior com Halteres Inclinado', 'gifs/trapezio/elevacao-de-deltoide-posterior-com-halteres-inclinado.gif'),
  ('Elevação de Deltoide em Y com Halteres Inclinado', 'gifs/trapezio/elevacao-de-deltoide-em-y-com-halteres-inclinado.gif'),
  ('Elevação de Joelho com Halteres', 'gifs/pernas/elevacao-de-joelho-com-halteres.gif'),
  ('Elevação de Panturrilha Sentado com Alavanca', 'gifs/panturrilhas/elevacao-de-panturrilha-sentado-com-alavanca.gif'),
  ('Elevação de Panturrilha Sentado com Barra', 'gifs/panturrilhas/elevacao-de-panturrilha-sentado-com-barra.gif'),
  ('Elevação de Panturrilha Sentado com Peso', 'gifs/panturrilhas/elevacao-de-panturrilha-sentado-com-peso.gif'),
  ('Elevação de Panturrilha com Barra em Pé', 'gifs/panturrilhas/elevacao-de-panturrilha-com-barra-em-pe.gif'),
  ('Elevação de Panturrilha com Faixa Elástica de Resistência', 'gifs/funcional-e-hit/elevacao-de-panturrilha-com-faixa-elastica-de-resistencia.gif'),
  ('Elevação de Panturrilha com Uma Perna na Máquina Hack', 'gifs/panturrilhas/elevacao-de-panturrilha-com-uma-perna-na-maquina-hack.gif'),
  ('Elevação de Panturrilha em Máquina em pé', 'gifs/panturrilhas/elevacao-de-panturrilha-em-maquina-em-pe.gif'),
  ('Elevação de Panturrilha em Uma Perna', 'gifs/calistenia/elevacao-de-panturrilha-em-uma-perna.gif'),
  ('Elevação de Panturrilha na Máquina', 'gifs/panturrilhas/elevacao-de-panturrilha-na-maquina.gif'),
  ('Elevação de Panturrilha no Leg Press', 'gifs/panturrilhas/elevacao-de-panturrilha-no-leg-press.gif'),
  ('Elevação de Panturrilha no Leg Press horizontal', 'gifs/panturrilhas/elevacao-de-panturrilha-no-leg-press-horizontal.gif'),
  ('Elevação de Panturrilha no Smith', 'gifs/panturrilhas/elevacao-de-panturrilha-no-smith.gif'),
  ('Elevação de Panturrilhas', 'gifs/panturrilhas/elevacao-de-panturrilhas.gif'),
  ('Elevação de Panturrilhas no Hack', 'gifs/panturrilhas/elevacao-de-panturrilhas-no-hack.gif'),
  ('Elevação de Perna Reta em Pé com Faixa de Resistência', 'gifs/funcional-e-hit/elevacao-de-perna-reta-em-pe-com-faixa-de-resistencia.gif'),
  ('Elevação de Perna em Pé com Alavanca', 'gifs/pernas/elevacao-de-perna-em-pe-com-alavanca.gif'),
  ('Elevação de Perna Única com Equilíbrio e Rosca de Bíceps', 'gifs/crossfit/elevacao-de-perna-unica-com-equilibrio-e-rosca-de-biceps.gif'),
  ('Elevação de Pernas deitado de Lado', 'gifs/funcional-e-hit/elevacao-de-pernas-deitado-de-lado.gif'),
  ('Elevação de Pernas estilo Sapo', 'gifs/funcional-e-hit/elevacao-de-pernas-estilo-sapo.gif'),
  ('Elevação de Quadril com Banda de Resistência de Joelhos', 'gifs/funcional-e-hit/elevacao-de-quadril-com-banda-de-resistencia-de-joelhos.gif'),
  ('Elevação de Quadril com Peso Corporal', 'gifs/calistenia/elevacao-de-quadril-com-peso-corporal.gif'),
  ('Elevação de T com Halteres Inclinada', 'gifs/trapezio/elevacao-de-t-com-halteres-inclinada.gif'),
  ('Elevação de panturrilha em pé', 'gifs/calistenia/elevacao-de-panturrilha-em-pe.gif'),
  ('Elevação frontal com barra girando', 'gifs/ombros/elevacao-frontal-com-barra-girando.gif'),
  ('Elevação frontal com barra w inclinada', 'gifs/ombros/elevacao-frontal-com-barra-w-inclinada.gif'),
  ('Elevação frontal com dois braços com halteres', 'gifs/ombros/elevacao-frontal-com-dois-bracos-com-halteres.gif'),
  ('Elevação frontal com halteres', 'gifs/ombros/elevacao-frontal-com-halteres.gif'),
  ('Elevação frontal com halteres sentado', 'gifs/ombros/elevacao-frontal-com-halteres-sentado.gif'),
  ('Elevação frontal lateral com elástico', 'gifs/funcional-e-hit/elevacao-frontal-lateral-com-elastico.gif'),
  ('Elevação lateral alternada com halteres', 'gifs/ombros/elevacao-lateral-alternada-com-halteres.gif'),
  ('Elevação lateral com barra no chão', 'gifs/ombros/elevacao-lateral-com-barra-no-chao.gif'),
  ('Elevação lateral com braço flexionado', 'gifs/ombros/elevacao-lateral-com-braco-flexionado.gif'),
  ('Elevação lateral com halteres com apoio no peito', 'gifs/ombros/elevacao-lateral-com-halteres-com-apoio-no-peito.gif'),
  ('Elevação lateral com halteres para deltoides posteriores deitado', 'gifs/ombros/elevacao-lateral-com-halteres-para-deltoides-posteriores-deitado.gif'),
  ('Elevação lateral com halteres sentado', 'gifs/ombros/elevacao-lateral-com-halteres-sentado.gif'),
  ('Elevação lateral com toalha na parede', 'gifs/calistenia/elevacao-lateral-com-toalha-na-parede.gif'),
  ('Elevação lateral com tronco inclinado', 'gifs/ombros/elevacao-lateral-com-tronco-inclinado.gif'),
  ('Elevação lateral cruzada no crossover', 'gifs/ombros/elevacao-lateral-cruzada-no-crossover.gif'),
  ('Elevação lateral de braços', 'gifs/funcional-e-hit/elevacao-lateral-de-bracos.gif'),
  ('Elevação lateral de braços com cabo', 'gifs/ombros/elevacao-lateral-de-bracos-com-cabo.gif'),
  ('Elevação lateral de braços com halteres', 'gifs/ombros/elevacao-lateral-de-bracos-com-halteres.gif'),
  ('Elevação lateral de deltóide posterior com halteres', 'gifs/mobilidade/elevacao-lateral-de-deltoide-posterior-com-halteres.gif'),
  ('Elevação lateral de halteres inclinada', 'gifs/ombros/elevacao-lateral-de-halteres-inclinada.gif'),
  ('Elevação lateral deitado', 'gifs/ombros/elevacao-lateral-deitado.gif'),
  ('Elevação lateral e frontal com halteres', 'gifs/ombros/elevacao-lateral-e-frontal-com-halteres.gif'),
  ('Elevação lateral na máquina', 'gifs/ombros/elevacao-lateral-na-maquina.gif'),
  ('Elevação lateral tronco inclinado', 'gifs/trapezio/elevacao-lateral-tronco-inclinado.gif'),
  ('Elevação lateral unilateral com cabo', 'gifs/ombros/elevacao-lateral-unilateral-com-cabo.gif'),
  ('Elevação lateral unilateral com haltere inclinado', 'gifs/ombros/elevacao-lateral-unilateral-com-haltere-inclinado.gif'),
  ('Elevação lateral unilateral com halteres', 'gifs/ombros/elevacao-lateral-unilateral-com-halteres.gif'),
  ('Elevações de ombros na paralela', 'gifs/calistenia/elevacoes-de-ombros-na-paralela.gif'),
  ('Elevações frontais com halteres apoiadas no peito', 'gifs/ombros/elevacoes-frontais-com-halteres-apoiadas-no-peito.gif'),
  ('Encolhimento Acima da Cabeça', 'gifs/trapezio/encolhimento-acima-da-cabeca.gif'),
  ('Encolhimento Inclinado Pronado', 'gifs/trapezio/encolhimento-inclinado-pronado.gif'),
  ('Encolhimento Sentado de Gittleson com Halteres', 'gifs/trapezio/encolhimento-sentado-de-gittleson-com-halteres.gif'),
  ('Encolhimento com Alavanca', 'gifs/trapezio/encolhimento-com-alavanca.gif'),
  ('Encolhimento com Cabo', 'gifs/trapezio/encolhimento-com-cabo.gif'),
  ('Encolhimento com Halteres', 'gifs/trapezio/encolhimento-com-halteres.gif'),
  ('Encolhimento com Halteres em Declive', 'gifs/trapezio/encolhimento-com-halteres-em-declive.gif'),
  ('Encolhimento de Barra', 'gifs/trapezio/encolhimento-de-barra.gif'),
  ('Encolhimento de Barra Atrás das Costas', 'gifs/trapezio/encolhimento-de-barra-atras-das-costas.gif'),
  ('Encolhimento de Ombros na Máquina Smith', 'gifs/trapezio/encolhimento-de-ombros-na-maquina-smith.gif'),
  ('Encolhimento de ombros por trás com barra', 'gifs/trapezio/encolhimento-de-ombros-por-tras-com-barra.gif'),
  ('Encolhimento na máquina', 'gifs/trapezio/encolhimento-na-maquina.gif'),
  ('Escalador de Montanha', 'gifs/funcional-e-hit/escalador-de-montanha.gif'),
  ('Esquiador com gymstick', 'gifs/funcional-e-hit/esquiador-com-gymstick.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Esteira Ergométrica', 'gifs/cardio/esteira-ergometrica.gif'),
  ('Esteira com Inclinação', 'gifs/cardio/esteira-com-inclinacao.gif'),
  ('Exercício Pliométrico X', 'gifs/funcional-e-hit/exercicio-pliometrico-x.gif'),
  ('Exercício de bailarina sentada', 'gifs/mobilidade/exercicio-de-bailarina-sentada.gif'),
  ('Exercício de retração escapular sentada', 'gifs/mobilidade/exercicio-de-retracao-escapular-sentada.gif'),
  ('Exercícios das 5 Marcas', 'gifs/funcional-e-hit/exercicios-das-5-marcas.gif'),
  ('Exercícios de Escada de Agilidade', 'gifs/funcional-e-hit/exercicios-de-escada-de-agilidade.gif'),
  ('Exercícios de escada de agilidade lateral', 'gifs/funcional-e-hit/exercicios-de-escada-de-agilidade-lateral.gif'),
  ('Extensão Concentrada com Cabo no Joelho', 'gifs/triceps/extensao-concentrada-com-cabo-no-joelho.gif'),
  ('Extensão De Glúteo Em Pé', 'gifs/funcional-e-hit/extensao-de-gluteo-em-pe.gif'),
  ('Extensão De Perna Reta', 'gifs/funcional-e-hit/extensao-de-perna-reta.gif'),
  ('Extensão Lombar com Peso', 'gifs/eretor-lombar/extensao-lombar-com-peso.gif'),
  ('Extensão de Perna Unilateral', 'gifs/pernas/extensao-de-perna-unilateral.gif'),
  ('Extensão de Perna em Pé com Faixa de Resistência', 'gifs/funcional-e-hit/extensao-de-perna-em-pe-com-faixa-de-resistencia.gif'),
  ('Extensão de Perna na Máquina Smith Reversa', 'gifs/gluteos/extensao-de-perna-na-maquina-smith-reversa.gif'),
  ('Extensão de Pernas Sentado com Faixa de Resistência', 'gifs/funcional-e-hit/extensao-de-pernas-sentado-com-faixa-de-resistencia.gif'),
  ('Extensão de Pernas com Faixa Elástica Sentado', 'gifs/funcional-e-hit/extensao-de-pernas-com-faixa-elastica-sentado.gif'),
  ('Extensão de Quadril com Cabo', 'gifs/gluteos/extensao-de-quadril-com-cabo.gif'),
  ('Extensão de Quadril em Pé com Alavanca', 'gifs/gluteos/extensao-de-quadril-em-pe-com-alavanca.gif'),
  ('Extensão de Quadril no Banco', 'gifs/funcional-e-hit/extensao-de-quadril-no-banco.gif'),
  ('Extensão de Tríceps Acima da Cabeça com Gymstick', 'gifs/funcional-e-hit/extensao-de-triceps-acima-da-cabeca-com-gymstick.gif'),
  ('Extensão de Tríceps Invertida com unilateral', 'gifs/triceps/extensao-de-triceps-invertida-com-unilateral.gif'),
  ('Extensão de Tríceps Testa Declinado Fechado', 'gifs/triceps/extensao-de-triceps-testa-declinado-fechado.gif'),
  ('Extensão de Tríceps com Cabo em Posição Ajoelhada', 'gifs/triceps/extensao-de-triceps-com-cabo-em-posicao-ajoelhada.gif'),
  ('Extensão de Tríceps com Cabos Cruzados', 'gifs/triceps/extensao-de-triceps-com-cabos-cruzados.gif'),
  ('Extensão de Tríceps com Faixa Elástica', 'gifs/funcional-e-hit/extensao-de-triceps-com-faixa-elastica.gif'),
  ('Extensão de Tríceps com Faixas Elásticas', 'gifs/funcional-e-hit/extensao-de-triceps-com-faixas-elasticas.gif'),
  ('Extensão de Tríceps com Uma Mão no Pulley Alto Sobre a Cabeça', 'gifs/triceps/extensao-de-triceps-com-uma-mao-no-pulley-alto-sobre-a-cabeca.gif'),
  ('Extensão de Tríceps com deitado com Barra', 'gifs/triceps/extensao-de-triceps-com-deitado-com-barra.gif'),
  ('Extensão de Tríceps deitado com Barra W Pegada Fechada atrás da Cabeça', 'gifs/triceps/extensao-de-triceps-deitado-com-barra-w-pegada-fechada-atras-da-cabeca.gif'),
  ('Extensão de Tríceps deitado com Corda', 'gifs/triceps/extensao-de-triceps-deitado-com-corda.gif'),
  ('Extensão de ombro com faixa', 'gifs/funcional-e-hit/extensao-de-ombro-com-faixa.gif'),
  ('Extensão de tríceps', 'gifs/calistenia/extensao-de-triceps.gif'),
  ('Extensão de tríceps com barra W inclinada', 'gifs/triceps/extensao-de-triceps-com-barra-w-inclinada.gif'),
  ('Extensão de tríceps com barra atrás da cabeça', 'gifs/triceps/extensao-de-triceps-com-barra-atras-da-cabeca.gif'),
  ('Extensão de tríceps com barra em pé', 'gifs/triceps/extensao-de-triceps-com-barra-em-pe.gif'),
  ('Extensão de tríceps com cabo ajoelhado', 'gifs/triceps/extensao-de-triceps-com-cabo-ajoelhado.gif'),
  ('Extensão de tríceps com cabo inclinado', 'gifs/triceps/extensao-de-triceps-com-cabo-inclinado.gif'),
  ('Extensão de tríceps com cabo na posição horizontal', 'gifs/triceps/extensao-de-triceps-com-cabo-na-posicao-horizontal.gif'),
  ('Extensão de tríceps com elástico na posição horizontal', 'gifs/funcional-e-hit/extensao-de-triceps-com-elastico-na-posicao-horizontal.gif'),
  ('Extensão de tríceps com haltere em pronação com um braço', 'gifs/triceps/extensao-de-triceps-com-haltere-em-pronacao-com-um-braco.gif'),
  ('Extensão de tríceps com haltere unilateral sentado', 'gifs/triceps/extensao-de-triceps-com-haltere-unilateral-sentado.gif'),
  ('Extensão de tríceps com pegada invertida', 'gifs/triceps/extensao-de-triceps-com-pegada-invertida.gif'),
  ('Extensão de tríceps com um braço', 'gifs/triceps/extensao-de-triceps-com-um-braco.gif'),
  ('Extensão de tríceps lateral com cabo', 'gifs/triceps/extensao-de-triceps-lateral-com-cabo.gif'),
  ('Extensão de tríceps na máquina', 'gifs/triceps/extensao-de-triceps-na-maquina.gif'),
  ('Extensão de tríceps na máquina pegada neutra', 'gifs/triceps/extensao-de-triceps-na-maquina-pegada-neutra.gif'),
  ('Extensão de tríceps no cabo alto', 'gifs/triceps/extensao-de-triceps-no-cabo-alto.gif'),
  ('Extensão de tríceps no cabo deitado', 'gifs/triceps/extensao-de-triceps-no-cabo-deitado.gif'),
  ('Extensão lombar sentada', 'gifs/eretor-lombar/extensao-lombar-sentada.gif'),
  ('Face Pull', 'gifs/trapezio/face-pull.gif'),
  ('Flexão', 'gifs/calistenia/flexao.gif'),
  ('Flexão Declinada', 'gifs/calistenia/flexao-declinada.gif'),
  ('Flexão Fechada com bola medicinal', 'gifs/calistenia/flexao-fechada-com-bola-medicinal.gif'),
  ('Flexão Invertida', 'gifs/calistenia/flexao-invertida.gif'),
  ('Flexão Nórdica', 'gifs/pernas/flexao-nordica.gif'),
  ('Flexão Nórdica (2)', 'gifs/pernas/flexao-nordica-2.gif'),
  ('Flexão alternada de ombro', 'gifs/mobilidade/flexao-alternada-de-ombro.gif'),
  ('Flexão cobra', 'gifs/funcional-e-hit/flexao-cobra.gif'),
  ('Flexão com Cruzamento dos Braços', 'gifs/calistenia/flexao-com-cruzamento-dos-bracos.gif'),
  ('Flexão com Rotação', 'gifs/funcional-e-hit/flexao-com-rotacao.gif'),
  ('Flexão com Toque no Peito', 'gifs/calistenia/flexao-com-toque-no-peito.gif'),
  ('Flexão com Toque nos Dedos dos Pés', 'gifs/calistenia/flexao-com-toque-nos-dedos-dos-pes.gif'),
  ('Flexão com barras de apoio', 'gifs/calistenia/flexao-com-barras-de-apoio.gif'),
  ('Flexão com kettlebell profunda', 'gifs/calistenia/flexao-com-kettlebell-profunda.gif'),
  ('Flexão com parada de mãos', 'gifs/calistenia/flexao-com-parada-de-maos.gif'),
  ('Flexão com peso', 'gifs/calistenia/flexao-com-peso.gif'),
  ('Flexão com um braço', 'gifs/calistenia/flexao-com-um-braco.gif'),
  ('Flexão de Braço Declinada com Bola de Estabilidade', 'gifs/calistenia/flexao-de-braco-declinada-com-bola-de-estabilidade.gif'),
  ('Flexão de Braço com Arqueamento', 'gifs/calistenia/flexao-de-braco-com-arqueamento.gif'),
  ('Flexão de Braço com Bola Medicinal com Apoio em Um Braço', 'gifs/calistenia/flexao-de-braco-com-bola-medicinal-com-apoio-em-um-braco.gif'),
  ('Flexão de Braço com Bola Medicinal em Um Braço', 'gifs/crossfit/flexao-de-braco-com-bola-medicinal-em-um-braco.gif'),
  ('Flexão de Braço com Bola de Estabilidade', 'gifs/calistenia/flexao-de-braco-com-bola-de-estabilidade.gif'),
  ('Flexão de Braço com Uma Perna', 'gifs/calistenia/flexao-de-braco-com-uma-perna.gif'),
  ('Flexão de Braço na Parede com Pegada Fechada', 'gifs/calistenia/flexao-de-braco-na-parede-com-pegada-fechada.gif'),
  ('Flexão de Braço no Bosu', 'gifs/funcional-e-hit/flexao-de-braco-no-bosu.gif'),
  ('Flexão de Braços com Apoio dos Joelhos Fechada', 'gifs/calistenia/flexao-de-bracos-com-apoio-dos-joelhos-fechada.gif'),
  ('Flexão de Braços com Toque no Ombro', 'gifs/calistenia/flexao-de-bracos-com-toque-no-ombro.gif'),
  ('Flexão de Cotovelos na Barra', 'gifs/calistenia/flexao-de-cotovelos-na-barra.gif'),
  ('Flexão de Dedos', 'gifs/calistenia/flexao-de-dedos.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Flexão de Parede', 'gifs/calistenia/flexao-de-parede.gif'),
  ('Flexão de Peito com TRX', 'gifs/calistenia/flexao-de-peito-com-trx.gif'),
  ('Flexão de Perna com Halteres em Decúbito Dorsal', 'gifs/calistenia/flexao-de-perna-com-halteres-em-decubito-dorsal.gif'),
  ('Flexão de Pernas com Alavanca', 'gifs/pernas/flexao-de-pernas-com-alavanca.gif'),
  ('Flexão de Pernas com Faixa Elástica', 'gifs/funcional-e-hit/flexao-de-pernas-com-faixa-elastica.gif'),
  ('Flexão de Pernas com Halteres Declinado', 'gifs/pernas/flexao-de-pernas-com-halteres-declinado.gif'),
  ('Flexão de Pernas deitado com Faixa Elástica', 'gifs/funcional-e-hit/flexao-de-pernas-deitado-com-faixa-elastica.gif'),
  ('Flexão de Pernas na Bola de Estabilidade', 'gifs/funcional-e-hit/flexao-de-pernas-na-bola-de-estabilidade.gif'),
  ('Flexão de Pulso Neutra Sentado com Halteres', 'gifs/antebracos/flexao-de-pulso-neutra-sentado-com-halteres.gif'),
  ('Flexão de Punho Fechado', 'gifs/calistenia/flexao-de-punho-fechado.gif'),
  ('Flexão de Punho Reversa com Anilha', 'gifs/antebracos/flexao-de-punho-reversa-com-anilha.gif'),
  ('Flexão de Punho Reversa com Barra Sobre um Banco', 'gifs/antebracos/flexao-de-punho-reversa-com-barra-sobre-um-banco.gif'),
  ('Flexão de Punho com Cabo em um Braço no Chão', 'gifs/antebracos/flexao-de-punho-com-cabo-em-um-braco-no-chao.gif'),
  ('Flexão de Punho com Halteres', 'gifs/antebracos/flexao-de-punho-com-halteres.gif'),
  ('Flexão de Queda', 'gifs/calistenia/flexao-de-queda.gif'),
  ('Flexão de apoio com elevação de braço', 'gifs/triceps/flexao-de-apoio-com-elevacao-de-braco.gif'),
  ('Flexão de braço com adução da escapula', 'gifs/calistenia/flexao-de-braco-com-aducao-da-escapula.gif'),
  ('Flexão de braço com as mãos entre bancos', 'gifs/crossfit/flexao-de-braco-com-as-maos-entre-bancos.gif'),
  ('Flexão de braço com palmas', 'gifs/calistenia/flexao-de-braco-com-palmas.gif'),
  ('Flexão de braço em posição de parada de mão com balanço', 'gifs/crossfit/flexao-de-braco-em-posicao-de-parada-de-mao-com-balanco.gif'),
  ('Flexão de diamante de joelhos', 'gifs/calistenia/flexao-de-diamante-de-joelhos.gif'),
  ('Flexão de joelhos', 'gifs/calistenia/flexao-de-joelhos.gif'),
  ('Flexão de ombro com faixa', 'gifs/funcional-e-hit/flexao-de-ombro-com-faixa.gif'),
  ('Flexão de pernas com toalha', 'gifs/calistenia/flexao-de-pernas-com-toalha.gif'),
  ('Flexão de pivô com banco', 'gifs/calistenia/flexao-de-pivo-com-banco.gif'),
  ('Flexão de pivô entre cadeiras', 'gifs/calistenia/flexao-de-pivo-entre-cadeiras.gif'),
  ('Flexão de um braço com apoio', 'gifs/calistenia/flexao-de-um-braco-com-apoio.gif'),
  ('Flexão de um braço com bola medicinal', 'gifs/calistenia/flexao-de-um-braco-com-bola-medicinal.gif'),
  ('Flexão diamante', 'gifs/calistenia/flexao-diamante.gif'),
  ('Flexão em pivô', 'gifs/calistenia/flexao-em-pivo.gif'),
  ('Flexão hindu modificada', 'gifs/calistenia/flexao-hindu-modificada.gif'),
  ('Flexão inclinada', 'gifs/calistenia/flexao-inclinada.gif'),
  ('Flexão na parede', 'gifs/calistenia/flexao-na-parede.gif'),
  ('Flexão plus', 'gifs/calistenia/flexao-plus.gif'),
  ('Flexão reversa com cotovelos', 'gifs/calistenia/flexao-reversa-com-cotovelos.gif'),
  ('Flexões de apoio de mão na parede', 'gifs/calistenia/flexoes-de-apoio-de-mao-na-parede.gif'),
  ('Flexões hindu', 'gifs/calistenia/flexoes-hindu.gif'),
  ('Gancho de Direita', 'gifs/funcional-e-hit/gancho-de-direita.gif'),
  ('Gluteos Coice nilateral Polia Baixa', 'gifs/gluteos/gluteos-coice-nilateral-polia-baixa.gif'),
  ('Glúteo Coice Na Alavanca', 'gifs/gluteos/gluteo-coice-na-alavanca.gif'),
  ('Glúteo Coice Na Máquina', 'gifs/gluteos/gluteo-coice-na-maquina.gif'),
  ('Glúteo Coice Na Máquina De Extensão De Pernas', 'gifs/gluteos/gluteo-coice-na-maquina-de-extensao-de-pernas.gif'),
  ('Glúteo Coice No Smith', 'gifs/gluteos/gluteo-coice-no-smith.gif'),
  ('Glúteo Coice com Gymstick', 'gifs/funcional-e-hit/gluteo-coice-com-gymstick.gif'),
  ('Glúteo Coice com Pernas Flexionada com Faixa', 'gifs/funcional-e-hit/gluteo-coice-com-pernas-flexionada-com-faixa.gif'),
  ('Glúteo Coice em Pé com Faixa Elástica', 'gifs/funcional-e-hit/gluteo-coice-em-pe-com-faixa-elastica.gif'),
  ('Glúteos Coice com Faixa Elástica', 'gifs/funcional-e-hit/gluteos-coice-com-faixa-elastica.gif'),
  ('Glúteos na Polia Baixa', 'gifs/gluteos/gluteos-na-polia-baixa.gif'),
  ('Hand Grip', 'gifs/antebracos/hand-grip.gif'),
  ('Hands Bike', 'gifs/cardio/hands-bike.gif'),
  ('Heaving Snatch Balance', 'gifs/crossfit/heaving-snatch-balance.gif'),
  ('Hiperextensão', 'gifs/eretor-lombar/hiperextensao.gif'),
  ('Hiperextensão Invertida de Sapo', 'gifs/eretor-lombar/hiperextensao-invertida-de-sapo.gif'),
  ('Hiperextensão Reversa com Faixa de Resistência', 'gifs/funcional-e-hit/hiperextensao-reversa-com-faixa-de-resistencia.gif'),
  ('Hiperextensão com Torção', 'gifs/eretor-lombar/hiperextensao-com-torcao.gif'),
  ('Hiperextensão de Lombar no Banco Plano', 'gifs/eretor-lombar/hiperextensao-de-lombar-no-banco-plano.gif'),
  ('Hiperextensão no Chão', 'gifs/eretor-lombar/hiperextensao-no-chao.gif'),
  ('Impossible Dips', 'gifs/calistenia/impossible-dips.gif'),
  ('Impulso com barra', 'gifs/crossfit/impulso-com-barra.gif'),
  ('Inclinação Lateral', 'gifs/mobilidade/inclinacao-lateral.gif'),
  ('Inclinação Lateral em Pé', 'gifs/mobilidade/inclinacao-lateral-em-pe.gif'),
  ('Inclinação Pélvica', 'gifs/funcional-e-hit/inclinacao-pelvica.gif'),
  ('Joelho Alternado no Peito', 'gifs/mobilidade/joelho-alternado-no-peito.gif'),
  ('Joelhos altos contra a parede', 'gifs/funcional-e-hit/joelhos-altos-contra-a-parede.gif'),
  ('Kettlebell Hang Clean', 'gifs/crossfit/kettlebell-hang-clean.gif'),
  ('Kettlebell em Forma de Oito', 'gifs/crossfit/kettlebell-em-forma-de-oito.gif'),
  ('Lançamento de Bola Medicinal deitado', 'gifs/funcional-e-hit/lancamento-de-bola-medicinal-deitado.gif'),
  ('Lançamento de bola medicinal', 'gifs/funcional-e-hit/lancamento-de-bola-medicinal.gif'),
  ('Leg Press', 'gifs/pernas/leg-press.gif'),
  ('Leg Press Alternado Deitado com Gymstick', 'gifs/funcional-e-hit/leg-press-alternado-deitado-com-gymstick.gif'),
  ('Leg Press Horizontal', 'gifs/pernas/leg-press-horizontal.gif'),
  ('Leg Press unilateral', 'gifs/pernas/leg-press-unilateral.gif'),
  ('Leg press 90 no smith', 'gifs/pernas/leg-press-90-no-smith.gif'),
  ('Levantamento Lateral de Perna em Quatro Apoios', 'gifs/funcional-e-hit/levantamento-lateral-de-perna-em-quatro-apoios.gif'),
  ('Levantamento Terra', 'gifs/costas/levantamento-terra.gif'),
  ('Levantamento Terra Romeno', 'gifs/costas/levantamento-terra-romeno.gif'),
  ('Levantamento Terra Sumô', 'gifs/pernas/levantamento-terra-sumo.gif'),
  ('Levantamento Terra Sumô com Halteres', 'gifs/pernas/levantamento-terra-sumo-com-halteres.gif'),
  ('Levantamento Terra Unilateral', 'gifs/calistenia/levantamento-terra-unilateral.gif'),
  ('Levantamento Terra Zercher', 'gifs/pernas/levantamento-terra-zercher.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Levantamento Terra com Alavanca', 'gifs/pernas/levantamento-terra-com-alavanca.gif'),
  ('Levantamento Terra com Barra Hexagonal', 'gifs/pernas/levantamento-terra-com-barra-hexagonal.gif'),
  ('Levantamento Terra com Barra no Landmine', 'gifs/pernas/levantamento-terra-com-barra-no-landmine.gif'),
  ('Levantamento Terra com Halteres', 'gifs/pernas/levantamento-terra-com-halteres.gif'),
  ('Levantamento Terra com Kettlebell', 'gifs/pernas/levantamento-terra-com-kettlebell.gif'),
  ('Levantamento Turco', 'gifs/crossfit/levantamento-turco.gif'),
  ('Levantamento com Suporte', 'gifs/pernas/levantamento-com-suporte.gif'),
  ('Levantamento de braço apoiado na parede', 'gifs/mobilidade/levantamento-de-braco-apoiado-na-parede.gif'),
  ('Levantamento de halteres de 3 maneiras', 'gifs/ombros/levantamento-de-halteres-de-3-maneiras.gif'),
  ('Levantamento de halteres de 4 maneiras (2)', 'gifs/ombros/levantamento-de-halteres-de-4-maneiras-2.gif'),
  ('Levantamento de panturrilha com alavanca', 'gifs/panturrilhas/levantamento-de-panturrilha-com-alavanca.gif'),
  ('Levantamento de panturrilha com apoio de banco', 'gifs/panturrilhas/levantamento-de-panturrilha-com-apoio-de-banco.gif'),
  ('Levantamento de panturrilha com apoio de uma perna', 'gifs/panturrilhas/levantamento-de-panturrilha-com-apoio-de-uma-perna.gif'),
  ('Levantamento de panturrilha com apoio e sobrecarga', 'gifs/calistenia/levantamento-de-panturrilha-com-apoio-e-sobrecarga.gif'),
  ('Levantamento frontal alternado com haltere sentado', 'gifs/ombros/levantamento-frontal-alternado-com-haltere-sentado.gif'),
  ('Levantamento frontal com anilha', 'gifs/ombros/levantamento-frontal-com-anilha.gif'),
  ('Levantamento frontal com barra', 'gifs/ombros/levantamento-frontal-com-barra.gif'),
  ('Levantamento frontal de cabo com dois braços', 'gifs/ombros/levantamento-frontal-de-cabo-com-dois-bracos.gif'),
  ('Levantamento frontal unilateral com cabo', 'gifs/ombros/levantamento-frontal-unilateral-com-cabo.gif'),
  ('Levantamento lateral com kettlebell', 'gifs/crossfit/levantamento-lateral-com-kettlebell.gif'),
  ('Levantamento terra romeno com halteres', 'gifs/pernas/levantamento-terra-romeno-com-halteres.gif'),
  ('Medicine Ball Rotational Throw', 'gifs/funcional-e-hit/medicine-ball-rotational-throw.gif'),
  ('Meio Agachado com Puxada para o Rosto no Cabo', 'gifs/trapezio/meio-agachado-com-puxada-para-o-rosto-no-cabo.gif'),
  ('Mergulho Coreano', 'gifs/calistenia/mergulho-coreano.gif'),
  ('Mergulho de peito assistido', 'gifs/peitoral/mergulho-de-peito-assistido.gif'),
  ('Mergulho de tríceps', 'gifs/calistenia/mergulho-de-triceps.gif'),
  ('Mergulho de tríceps com alavanca', 'gifs/triceps/mergulho-de-triceps-com-alavanca.gif'),
  ('Mergulho reverso', 'gifs/funcional-e-hit/mergulho-reverso.gif'),
  ('Mergulhos Assistidos para Tríceps', 'gifs/triceps/mergulhos-assistidos-para-triceps.gif'),
  ('Mergulhos para tríceps no chão', 'gifs/calistenia/mergulhos-para-triceps-no-chao.gif'),
  ('Mesa Flexora Unilateral', 'gifs/pernas/mesa-flexora-unilateral.gif'),
  ('Mesa flexora', 'gifs/pernas/mesa-flexora.gif'),
  ('Minhoca', 'gifs/funcional-e-hit/minhoca.gif'),
  ('Moinho com Kettlebell', 'gifs/crossfit/moinho-com-kettlebell.gif'),
  ('Moinho de vento com haltere', 'gifs/crossfit/moinho-de-vento-com-haltere.gif'),
  ('Muscle Snatch', 'gifs/crossfit/muscle-snatch.gif'),
  ('Muscle up', 'gifs/calistenia/muscle-up.gif'),
  ('Máquina Elíptica', 'gifs/cardio/maquina-eliptica.gif'),
  ('Máquina Simulador Escada', 'gifs/cardio/maquina-simulador-escada.gif'),
  ('Máquina de Abdução de Quadril', 'gifs/gluteos/maquina-de-abducao-de-quadril.gif'),
  ('Máquina de Adução de Quadril', 'gifs/pernas/maquina-de-aducao-de-quadril.gif'),
  ('Máquina de Caminhada Ondulatório', 'gifs/cardio/maquina-de-caminhada-ondulatorio.gif'),
  ('Máquina de Flexão de Perna Unilateral', 'gifs/pernas/maquina-de-flexao-de-perna-unilateral.gif'),
  ('Máquina de elevação lateral', 'gifs/ombros/maquina-de-elevacao-lateral.gif'),
  ('Máquina de flexão de tríceps', 'gifs/triceps/maquina-de-flexao-de-triceps.gif'),
  ('Máquina de remo', 'gifs/costas/maquina-de-remo.gif'),
  ('Máquina de rosca direta', 'gifs/biceps/maquina-de-rosca-direta.gif'),
  ('Máquina de voador de peito inclinado', 'gifs/peitoral/maquina-de-voador-de-peito-inclinado.gif'),
  ('Nave Seal Burpee', 'gifs/funcional-e-hit/nave-seal-burpee.gif'),
  ('Panturrilha em Pé no Smith', 'gifs/panturrilhas/panturrilha-em-pe-no-smith.gif'),
  ('Panturrilhas em Pé', 'gifs/panturrilhas/panturrilhas-em-pe.gif'),
  ('Paralela', 'gifs/calistenia/paralela.gif'),
  ('Paralelas', 'gifs/peitoral/paralelas.gif'),
  ('Paralelas entre Cadeiras', 'gifs/calistenia/paralelas-entre-cadeiras.gif'),
  ('Paralelas na Argola', 'gifs/calistenia/paralelas-na-argola.gif'),
  ('Paralelas na Barra', 'gifs/calistenia/paralelas-na-barra.gif'),
  ('Passagem de Bola Medicinal de Peito em Pé', 'gifs/funcional-e-hit/passagem-de-bola-medicinal-de-peito-em-pe.gif'),
  ('Passo Invertido com Elevação do Joelho', 'gifs/funcional-e-hit/passo-invertido-com-elevacao-do-joelho.gif'),
  ('Passo Lateral em Alta Velocidade', 'gifs/funcional-e-hit/passo-lateral-em-alta-velocidade.gif'),
  ('Passo de Esqui', 'gifs/funcional-e-hit/passo-de-esqui.gif'),
  ('Patinador', 'gifs/funcional-e-hit/patinador.gif'),
  ('Peso muerto piernas rígidas con barra', 'gifs/pernas/peso-muerto-piernas-rigidas-con-barra.gif'),
  ('Planche', 'gifs/calistenia/planche.gif'),
  ('Planche com Flexão de Braço', 'gifs/calistenia/planche-com-flexao-de-braco.gif'),
  ('Plataforma Vibratória', 'gifs/cardio/plataforma-vibratoria.gif'),
  ('Polichinelo Frontal', 'gifs/funcional-e-hit/polichinelo-frontal.gif'),
  ('Polichinelos', 'gifs/funcional-e-hit/polichinelos.gif'),
  ('Ponte Unilateral Com Uma Perna Levantada', 'gifs/funcional-e-hit/ponte-unilateral-com-uma-perna-levantada.gif'),
  ('Ponte Unilateral no Banco', 'gifs/funcional-e-hit/ponte-unilateral-no-banco.gif'),
  ('Ponte com Faixa Elástica', 'gifs/funcional-e-hit/ponte-com-faixa-elastica.gif'),
  ('Ponte com Halteres', 'gifs/gluteos/ponte-com-halteres.gif'),
  ('Ponte de Glúteos', 'gifs/funcional-e-hit/ponte-de-gluteos.gif'),
  ('Ponte de Glúteos com Barra', 'gifs/pernas/ponte-de-gluteos-com-barra.gif'),
  ('Ponte em Unilateral', 'gifs/calistenia/ponte-em-unilateral.gif'),
  ('Postura da Cobra - Alongamento Abdominal', 'gifs/mobilidade/postura-da-cobra-alongamento-abdominal.gif'),
  ('Postura da Virilha Sentada', 'gifs/mobilidade/postura-da-virilha-sentada.gif'),
  ('Postura de meio sapo', 'gifs/mobilidade/postura-de-meio-sapo.gif'),
  ('Postura de peixe', 'gifs/mobilidade/postura-de-peixe.gif'),
  ('Postura do Arco', 'gifs/mobilidade/postura-do-arco.gif'),
  ('Postura do Arco Oscilante', 'gifs/mobilidade/postura-do-arco-oscilante.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Postura do Bebê Feliz', 'gifs/mobilidade/postura-do-bebe-feliz.gif'),
  ('Postura do sapo', 'gifs/mobilidade/postura-do-sapo.gif'),
  ('Power Clean', 'gifs/crossfit/power-clean.gif'),
  ('Pressão Unilateral Assistida por Alavanca', 'gifs/pernas/pressao-unilateral-assistida-por-alavanca.gif'),
  ('Protração e retração da escápula', 'gifs/mobilidade/protracao-e-retracao-da-escapula.gif'),
  ('Pular Corda', 'gifs/crossfit/pular-corda.gif'),
  ('Pull Up', 'gifs/costas/pull-up.gif'),
  ('Pulldown Unilateral no Cabo', 'gifs/costas/pulldown-unilateral-no-cabo.gif'),
  ('Pulldown com corda', 'gifs/costas/pulldown-com-corda.gif'),
  ('Pulldown inclinado com corda', 'gifs/costas/pulldown-inclinado-com-corda.gif'),
  ('Pullover com Barra', 'gifs/costas/pullover-com-barra.gif'),
  ('Pullover com Barra W Pegada invertida', 'gifs/costas/pullover-com-barra-w-pegada-invertida.gif'),
  ('Pullover com Cabo', 'gifs/costas/pullover-com-cabo.gif'),
  ('Pullover com Halteres na Bola de Estabilidade', 'gifs/peitoral/pullover-com-halteres-na-bola-de-estabilidade.gif'),
  ('Pullover com barra no banco declinado', 'gifs/costas/pullover-com-barra-no-banco-declinado.gif'),
  ('Pullover com cabo sentado', 'gifs/costas/pullover-com-cabo-sentado.gif'),
  ('Pullover com haltere', 'gifs/peitoral/pullover-com-haltere.gif'),
  ('Pullover de braço reto com halteres (joelhos a 90 graus)', 'gifs/peitoral/pullover-de-braco-reto-com-halteres-joelhos-a-90-graus.gif'),
  ('Pullover na Máquina de Alavanca', 'gifs/costas/pullover-na-maquina-de-alavanca.gif'),
  ('Pulo de impulso de quadril de uma perna', 'gifs/calistenia/pulo-de-impulso-de-quadril-de-uma-perna.gif'),
  ('Pulos com Abertura de Pernas', 'gifs/funcional-e-hit/pulos-com-abertura-de-pernas.gif'),
  ('Pulos de Joelho Elevado', 'gifs/funcional-e-hit/pulos-de-joelho-elevado.gif'),
  ('Puxada Alta', 'gifs/costas/puxada-alta.gif'),
  ('Puxada Alta Invertida', 'gifs/costas/puxada-alta-invertida.gif'),
  ('Puxada Alta Neutra com Cabos Duplos no Chão', 'gifs/costas/puxada-alta-neutra-com-cabos-duplos-no-chao.gif'),
  ('Puxada Alta com Alavanca', 'gifs/costas/puxada-alta-com-alavanca.gif'),
  ('Puxada Alta com Triângulo', 'gifs/costas/puxada-alta-com-triangulo.gif'),
  ('Puxada Alta com Um Joelho Apoiado', 'gifs/costas/puxada-alta-com-um-joelho-apoiado.gif'),
  ('Puxada De Cabo Ajoelhada', 'gifs/gluteos/puxada-de-cabo-ajoelhada.gif'),
  ('Puxada Front Lever', 'gifs/calistenia/puxada-front-lever.gif'),
  ('Puxada ajoelhada com banda de resistência', 'gifs/funcional-e-hit/puxada-ajoelhada-com-banda-de-resistencia.gif'),
  ('Puxada alta na Máquina Nuca', 'gifs/costas/puxada-alta-na-maquina-nuca.gif'),
  ('Puxada alta na polia nuca', 'gifs/costas/puxada-alta-na-polia-nuca.gif'),
  ('Puxada alta unilateral alta ajoelhada', 'gifs/costas/puxada-alta-unilateral-alta-ajoelhada.gif'),
  ('Puxada com Faixa Elástica', 'gifs/funcional-e-hit/puxada-com-faixa-elastica.gif'),
  ('Puxada com Halteres entre as Pernas', 'gifs/crossfit/puxada-com-halteres-entre-as-pernas.gif'),
  ('Puxada com Um Braço com Cabo', 'gifs/costas/puxada-com-um-braco-com-cabo.gif'),
  ('Puxada com Um Braço com Peso Adicional', 'gifs/costas/puxada-com-um-braco-com-peso-adicional.gif'),
  ('Puxada de face com cabo cruzado', 'gifs/trapezio/puxada-de-face-com-cabo-cruzado.gif'),
  ('Puxada em Pé com Torção no Cabo', 'gifs/costas/puxada-em-pe-com-torcao-no-cabo.gif'),
  ('Puxada escapular na barra fixa', 'gifs/calistenia/puxada-escapular-na-barra-fixa.gif'),
  ('Puxada isométrica', 'gifs/calistenia/puxada-isometrica.gif'),
  ('Puxada na Polia Alta com Pegada Fechada', 'gifs/costas/puxada-na-polia-alta-com-pegada-fechada.gif'),
  ('Puxada para o Rosto de Joelhos', 'gifs/trapezio/puxada-para-o-rosto-de-joelhos.gif'),
  ('Puxar com Faixa Elástica', 'gifs/funcional-e-hit/puxar-com-faixa-elastica.gif'),
  ('Pêndulo de ombro', 'gifs/mobilidade/pendulo-de-ombro.gif'),
  ('Quadrúpede com elevação de braço e perna contralateral', 'gifs/funcional-e-hit/quadrupede-com-elevacao-de-braco-e-perna-contralateral.gif'),
  ('Quatro Apoios', 'gifs/gluteos/quatro-apoios.gif'),
  ('Rastejo de Urso', 'gifs/funcional-e-hit/rastejo-de-urso.gif'),
  ('Remada Alta (1)', 'gifs/ombros/remada-alta-1.gif'),
  ('Remada Alta Com Barra W', 'gifs/trapezio/remada-alta-com-barra-w.gif'),
  ('Remada Alta com Cabo', 'gifs/trapezio/remada-alta-com-cabo.gif'),
  ('Remada Alta com Halter', 'gifs/trapezio/remada-alta-com-halter.gif'),
  ('Remada Curvada Inclinada com Barra', 'gifs/costas/remada-curvada-inclinada-com-barra.gif'),
  ('Remada Curvada com Barra', 'gifs/costas/remada-curvada-com-barra.gif'),
  ('Remada Curvada com Pegada Invertida na Barra', 'gifs/costas/remada-curvada-com-pegada-invertida-na-barra.gif'),
  ('Remada Curvada em T', 'gifs/costas/remada-curvada-em-t.gif'),
  ('Remada Curvada no Smith', 'gifs/costas/remada-curvada-no-smith.gif'),
  ('Remada Inclinada a 45 Graus', 'gifs/trapezio/remada-inclinada-a-45-graus.gif'),
  ('Remada Inclinada com Cabo', 'gifs/costas/remada-inclinada-com-cabo.gif'),
  ('Remada Inclinada com Pegada Neutra com Halteres', 'gifs/costas/remada-inclinada-com-pegada-neutra-com-halteres.gif'),
  ('Remada Inclinada com Pegada Reversa com Halteres', 'gifs/costas/remada-inclinada-com-pegada-reversa-com-halteres.gif'),
  ('Remada Inclinada no banco com Cabo', 'gifs/costas/remada-inclinada-no-banco-com-cabo.gif'),
  ('Remada Invertida', 'gifs/costas/remada-invertida.gif'),
  ('Remada Invertida Com Argolas', 'gifs/calistenia/remada-invertida-com-argolas.gif'),
  ('Remada Invertida na Mesa', 'gifs/calistenia/remada-invertida-na-mesa.gif'),
  ('Remada Renegada com Halteres', 'gifs/costas/remada-renegada-com-halteres.gif'),
  ('Remada Sentada com Anilhas', 'gifs/costas/remada-sentada-com-anilhas.gif'),
  ('Remada Sentada com Cabo', 'gifs/costas/remada-sentada-com-cabo.gif'),
  ('Remada Sentada com Corda na Polia', 'gifs/costas/remada-sentada-com-corda-na-polia.gif'),
  ('Remada Sentada na Máquina', 'gifs/costas/remada-sentada-na-maquina.gif'),
  ('Remada T com Landmine', 'gifs/costas/remada-t-com-landmine.gif'),
  ('Remada T com alavanca', 'gifs/costas/remada-t-com-alavanca.gif'),
  ('Remada T invertida com alavanca', 'gifs/costas/remada-t-invertida-com-alavanca.gif'),
  ('Remada Unilateral com Barra', 'gifs/costas/remada-unilateral-com-barra.gif'),
  ('Remada Unilateral com Cabo', 'gifs/costas/remada-unilateral-com-cabo.gif'),
  ('Remada afastada com banda de resistência', 'gifs/funcional-e-hit/remada-afastada-com-banda-de-resistencia.gif'),
  ('Remada alta com halteres unilateral', 'gifs/trapezio/remada-alta-com-halteres-unilateral.gif'),
  ('Remada com Cabo Sentada Unilateral com Torção', 'gifs/costas/remada-com-cabo-sentada-unilateral-com-torcao.gif'),
  ('Remada com Halteres em Posição Prancha', 'gifs/costas/remada-com-halteres-em-posicao-prancha.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Remada com banda de resistência curvada para deltoides posterior', 'gifs/funcional-e-hit/remada-com-banda-de-resistencia-curvada-para-deltoides-posterior.gif'),
  ('Remada com barra', 'gifs/trapezio/remada-com-barra.gif'),
  ('Remada com barra curvada para trás', 'gifs/crossfit/remada-com-barra-curvada-para-tras.gif'),
  ('Remada com halteres para a posterior de ombros', 'gifs/ombros/remada-com-halteres-para-a-posterior-de-ombros.gif'),
  ('Remada com o Peso do Corpo na Porta', 'gifs/calistenia/remada-com-o-peso-do-corpo-na-porta.gif'),
  ('Remada cruzada no cross', 'gifs/costas/remada-cruzada-no-cross.gif'),
  ('Remada curvada com barra de pegada alternada ampla com adução de escapula', 'gifs/costas/remada-curvada-com-barra-de-pegada-alternada-ampla-com-aducao-de-escapula.gif'),
  ('Remada curvada com halteres', 'gifs/costas/remada-curvada-com-halteres.gif'),
  ('Remada curvada com halteres com pegada invertida', 'gifs/costas/remada-curvada-com-halteres-com-pegada-invertida.gif'),
  ('Remada curvada com kettlebell', 'gifs/costas/remada-curvada-com-kettlebell.gif'),
  ('Remada de deltoide posterior sentado com haltere', 'gifs/ombros/remada-de-deltoide-posterior-sentado-com-haltere.gif'),
  ('Remada de espingarda', 'gifs/costas/remada-de-espingarda.gif'),
  ('Remada em Y com cabo', 'gifs/trapezio/remada-em-y-com-cabo.gif'),
  ('Remada frontal com alavanca', 'gifs/costas/remada-frontal-com-alavanca.gif'),
  ('Remada inclinada a 45 graus', 'gifs/ombros/remada-inclinada-a-45-graus.gif'),
  ('Remada inversa com cabos deitado', 'gifs/ombros/remada-inversa-com-cabos-deitado.gif'),
  ('Remada invertida com cable inclinado', 'gifs/trapezio/remada-invertida-com-cable-inclinado.gif'),
  ('Remada lateral com halteres sentado', 'gifs/ombros/remada-lateral-com-halteres-sentado.gif'),
  ('Remada sentada com faixa', 'gifs/funcional-e-hit/remada-sentada-com-faixa.gif'),
  ('Remada sentado com cabo pegada fechada', 'gifs/costas/remada-sentado-com-cabo-pegada-fechada.gif'),
  ('Remada unilateral com barra landmine', 'gifs/costas/remada-unilateral-com-barra-landmine.gif'),
  ('Remada unilateral com gymstick', 'gifs/funcional-e-hit/remada-unilateral-com-gymstick.gif'),
  ('Rolagem de espuma para isquiotibiais', 'gifs/mobilidade/rolagem-de-espuma-para-isquiotibiais.gif'),
  ('Rolamento de Espuma para Panturrilhas', 'gifs/mobilidade/rolamento-de-espuma-para-panturrilhas.gif'),
  ('Rolamento de espuma nas costas', 'gifs/mobilidade/rolamento-de-espuma-nas-costas.gif'),
  ('Rolamento de espuma nos quadríceps', 'gifs/mobilidade/rolamento-de-espuma-nos-quadriceps.gif'),
  ('Rolamento de espuma nos romboides', 'gifs/mobilidade/rolamento-de-espuma-nos-romboides.gif'),
  ('Rolamento na bola suíça', 'gifs/funcional-e-hit/rolamento-na-bola-suica.gif'),
  ('Rolando como uma Bola', 'gifs/mobilidade/rolando-como-uma-bola.gif'),
  ('Rolinho de antebraço', 'gifs/antebracos/rolinho-de-antebraco.gif'),
  ('Rolo de Espuma para os Glúteos', 'gifs/mobilidade/rolo-de-espuma-para-os-gluteos.gif'),
  ('Rolo de espuma ombro posterior', 'gifs/mobilidade/rolo-de-espuma-ombro-posterior.gif'),
  ('Rolo de espuma para fascite plantar', 'gifs/mobilidade/rolo-de-espuma-para-fascite-plantar.gif'),
  ('Rolo de espuma para ombro e peito frontal', 'gifs/mobilidade/rolo-de-espuma-para-ombro-e-peito-frontal.gif'),
  ('Rosca Banco Inclinado', 'gifs/biceps/rosca-banco-inclinado.gif'),
  ('Rosca Bilateral com Cabo em Banco Inclinado', 'gifs/biceps/rosca-bilateral-com-cabo-em-banco-inclinado.gif'),
  ('Rosca Concentrada com Pegada Fechada Sentado', 'gifs/biceps/rosca-concentrada-com-pegada-fechada-sentado.gif'),
  ('Rosca Direta com Barra', 'gifs/biceps/rosca-direta-com-barra.gif'),
  ('Rosca Direta com Barra deitado em Banco Alto', 'gifs/biceps/rosca-direta-com-barra-deitado-em-banco-alto.gif'),
  ('Rosca Direta com Barra em Pegada Fechada', 'gifs/biceps/rosca-direta-com-barra-em-pegada-fechada.gif'),
  ('Rosca Direta com Barra no colete scott', 'gifs/biceps/rosca-direta-com-barra-no-colete-scott.gif'),
  ('Rosca Direta com Cabo deitado', 'gifs/biceps/rosca-direta-com-cabo-deitado.gif'),
  ('Rosca Inversa com Barra', 'gifs/antebracos/rosca-inversa-com-barra.gif'),
  ('Rosca Inversa com Halteres', 'gifs/biceps/rosca-inversa-com-halteres.gif'),
  ('Rosca Scott com Alavanca', 'gifs/biceps/rosca-scott-com-alavanca.gif'),
  ('Rosca Scott com Barra W', 'gifs/biceps/rosca-scott-com-barra-w.gif'),
  ('Rosca Scott com Halteres Martelo no Banco', 'gifs/biceps/rosca-scott-com-halteres-martelo-no-banco.gif'),
  ('Rosca Unilateral com Cabo', 'gifs/biceps/rosca-unilateral-com-cabo.gif'),
  ('Rosca Zottman', 'gifs/biceps/rosca-zottman.gif'),
  ('Rosca alternada com barra', 'gifs/biceps/rosca-alternada-com-barra.gif'),
  ('Rosca alternada com halteres sentado', 'gifs/biceps/rosca-alternada-com-halteres-sentado.gif'),
  ('Rosca bíceps alta com halteres', 'gifs/biceps/rosca-biceps-alta-com-halteres.gif'),
  ('Rosca bíceps com cabo ajoelhado', 'gifs/biceps/rosca-biceps-com-cabo-ajoelhado.gif'),
  ('Rosca bíceps com faixa elástica', 'gifs/funcional-e-hit/rosca-biceps-com-faixa-elastica.gif'),
  ('Rosca bíceps com halteres', 'gifs/biceps/rosca-biceps-com-halteres.gif'),
  ('Rosca bíceps com pegada fechada na barra W', 'gifs/biceps/rosca-biceps-com-pegada-fechada-na-barra-w.gif'),
  ('Rosca bíceps inclinada com cabos', 'gifs/biceps/rosca-biceps-inclinada-com-cabos.gif'),
  ('Rosca bíceps inclinada com halteres sentado', 'gifs/biceps/rosca-biceps-inclinada-com-halteres-sentado.gif'),
  ('Rosca bíceps sentado', 'gifs/biceps/rosca-biceps-sentado.gif'),
  ('Rosca bíceps unilateral', 'gifs/biceps/rosca-biceps-unilateral.gif'),
  ('Rosca bíceps unilateral com pegada invertida em cabo', 'gifs/biceps/rosca-biceps-unilateral-com-pegada-invertida-em-cabo.gif'),
  ('Rosca bíceps unilateral no cabo alto', 'gifs/biceps/rosca-biceps-unilateral-no-cabo-alto.gif'),
  ('Rosca com Polia Alta', 'gifs/biceps/rosca-com-polia-alta.gif'),
  ('Rosca com barra', 'gifs/biceps/rosca-com-barra.gif'),
  ('Rosca com cabo de um braço', 'gifs/biceps/rosca-com-cabo-de-um-braco.gif'),
  ('Rosca com halteres', 'gifs/biceps/rosca-com-halteres.gif'),
  ('Rosca com halteres no colete scott', 'gifs/biceps/rosca-com-halteres-no-colete-scott.gif'),
  ('Rosca concentrada', 'gifs/biceps/rosca-concentrada.gif'),
  ('Rosca concentrada com cabo', 'gifs/biceps/rosca-concentrada-com-cabo.gif'),
  ('Rosca concentrada com perna', 'gifs/calistenia/rosca-concentrada-com-perna.gif'),
  ('Rosca concentrada unilateral com cabo', 'gifs/biceps/rosca-concentrada-unilateral-com-cabo.gif'),
  ('Rosca de Bíceps com Halteres no Banco Scott', 'gifs/biceps/rosca-de-biceps-com-halteres-no-banco-scott.gif'),
  ('Rosca de Bíceps com Puxada de Cabo', 'gifs/biceps/rosca-de-biceps-com-puxada-de-cabo.gif'),
  ('Rosca de Dedos com Halteres', 'gifs/antebracos/rosca-de-dedos-com-halteres.gif'),
  ('Rosca de Punho Pegada Neutra com Anilhas', 'gifs/antebracos/rosca-de-punho-pegada-neutra-com-anilhas.gif'),
  ('Rosca de Punho Reversa com Barra', 'gifs/antebracos/rosca-de-punho-reversa-com-barra.gif'),
  ('Rosca de Punho com Barra Atrás das Costas', 'gifs/antebracos/rosca-de-punho-com-barra-atras-das-costas.gif'),
  ('Rosca de bíceps com alavanca', 'gifs/biceps/rosca-de-biceps-com-alavanca.gif'),
  ('Rosca de bíceps unilateral com faixa de resistência', 'gifs/funcional-e-hit/rosca-de-biceps-unilateral-com-faixa-de-resistencia.gif'),
  ('Rosca de dedo com barra', 'gifs/antebracos/rosca-de-dedo-com-barra.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Rosca de punho com barra', 'gifs/antebracos/rosca-de-punho-com-barra.gif'),
  ('Rosca direta com barra w', 'gifs/biceps/rosca-direta-com-barra-w.gif'),
  ('Rosca inversa com barra W', 'gifs/biceps/rosca-inversa-com-barra-w.gif'),
  ('Rosca martelo', 'gifs/biceps/rosca-martelo.gif'),
  ('Rosca martelo com corda', 'gifs/biceps/rosca-martelo-com-corda.gif'),
  ('Rosca martelo com faixa de resistência', 'gifs/funcional-e-hit/rosca-martelo-com-faixa-de-resistencia.gif'),
  ('Rosca martelo com garrafa de água', 'gifs/funcional-e-hit/rosca-martelo-com-garrafa-de-agua.gif'),
  ('Rosca martelo com halter no colete scott', 'gifs/biceps/rosca-martelo-com-halter-no-colete-scott.gif'),
  ('Rosca martelo com halteres no banco scott', 'gifs/biceps/rosca-martelo-com-halteres-no-banco-scott.gif'),
  ('Rosca martelo sentada', 'gifs/biceps/rosca-martelo-sentada.gif'),
  ('Rosca no Cabo', 'gifs/biceps/rosca-no-cabo.gif'),
  ('Rosca pronada no banco inclinado', 'gifs/biceps/rosca-pronada-no-banco-inclinado.gif'),
  ('Rosca scott alternados com halteres', 'gifs/biceps/rosca-scott-alternados-com-halteres.gif'),
  ('Rosca scott com halteres', 'gifs/biceps/rosca-scott-com-halteres.gif'),
  ('Rosca scott unilateral com halteres', 'gifs/biceps/rosca-scott-unilateral-com-halteres.gif'),
  ('Rosca spider com único haltere', 'gifs/biceps/rosca-spider-com-unico-haltere.gif'),
  ('Rosca spider unilateral', 'gifs/biceps/rosca-spider-unilateral.gif'),
  ('Rotação Externa De Quadril Com Faixa Elástica', 'gifs/mobilidade/rotacao-externa-de-quadril-com-faixa-elastica.gif'),
  ('Rotação Externa de Ombro com Cabo', 'gifs/mobilidade/rotacao-externa-de-ombro-com-cabo.gif'),
  ('Rotação Externa de Quadril Sentado com Faixa Elástica', 'gifs/mobilidade/rotacao-externa-de-quadril-sentado-com-faixa-elastica.gif'),
  ('Rotação Externa do Pé com Faixa Elástica', 'gifs/mobilidade/rotacao-externa-do-pe-com-faixa-elastica.gif'),
  ('Rotação Interna do Quadril Sentado com Faixa Elástica', 'gifs/mobilidade/rotacao-interna-do-quadril-sentado-com-faixa-elastica.gif'),
  ('Rotação da coluna torácica de joelhos', 'gifs/mobilidade/rotacao-da-coluna-toracica-de-joelhos.gif'),
  ('Rotação de Pé e Tornozelo', 'gifs/mobilidade/rotacao-de-pe-e-tornozelo.gif'),
  ('Rotação do corpo superior deitado', 'gifs/mobilidade/rotacao-do-corpo-superior-deitado.gif'),
  ('Rotação em Pé', 'gifs/mobilidade/rotacao-em-pe.gif'),
  ('Rotação espinhal deitado', 'gifs/mobilidade/rotacao-espinhal-deitado.gif'),
  ('Rotação externa com cabo a 90 graus', 'gifs/mobilidade/rotacao-externa-com-cabo-a-90-graus.gif'),
  ('Rotação externa com cabo em posição de joelhos', 'gifs/mobilidade/rotacao-externa-com-cabo-em-posicao-de-joelhos.gif'),
  ('Rotação externa de halteres apoiada no banco', 'gifs/mobilidade/rotacao-externa-de-halteres-apoiada-no-banco.gif'),
  ('Rotação externa de ombro com faixa elástica', 'gifs/mobilidade/rotacao-externa-de-ombro-com-faixa-elastica.gif'),
  ('Rotação externa do ombro', 'gifs/mobilidade/rotacao-externa-do-ombro.gif'),
  ('Rotação externa do ombro deitado com haltere', 'gifs/mobilidade/rotacao-externa-do-ombro-deitado-com-haltere.gif'),
  ('Rotação interna de cabo a 90 graus', 'gifs/mobilidade/rotacao-interna-de-cabo-a-90-graus.gif'),
  ('Rotação interna de ombro com cabo', 'gifs/mobilidade/rotacao-interna-de-ombro-com-cabo.gif'),
  ('Rotação interna do ombro', 'gifs/mobilidade/rotacao-interna-do-ombro.gif'),
  ('Rotação interna do ombro sentada com cabo', 'gifs/mobilidade/rotacao-interna-do-ombro-sentada-com-cabo.gif'),
  ('Rotação para trás de joelhos', 'gifs/mobilidade/rotacao-para-tras-de-joelhos.gif'),
  ('Salto com Joelhos Flexionados', 'gifs/funcional-e-hit/salto-com-joelhos-flexionados.gif'),
  ('Salto com halteres dividido', 'gifs/funcional-e-hit/salto-com-halteres-dividido.gif'),
  ('Salto em Agachamento com Joelhos Flexionados', 'gifs/funcional-e-hit/salto-em-agachamento-com-joelhos-flexionados.gif'),
  ('Salto em Caixa com uma Perna', 'gifs/calistenia/salto-em-caixa-com-uma-perna.gif'),
  ('Salto em Distância', 'gifs/calistenia/salto-em-distancia.gif'),
  ('Salto em Uma Perna para a Frente', 'gifs/funcional-e-hit/salto-em-uma-perna-para-a-frente.gif'),
  ('Salto na Caixa', 'gifs/crossfit/salto-na-caixa.gif'),
  ('Salto na Caixa para Agachamento Pistola', 'gifs/calistenia/salto-na-caixa-para-agachamento-pistola.gif'),
  ('Salto para Caixa 2 para 1', 'gifs/calistenia/salto-para-caixa-2-para-1.gif'),
  ('Salto para Trás', 'gifs/funcional-e-hit/salto-para-tras.gif'),
  ('Saltos Pliométricos em Zigue-Zague', 'gifs/funcional-e-hit/saltos-pliometricos-em-zigue-zague.gif'),
  ('Saltos Potentes', 'gifs/funcional-e-hit/saltos-potentes.gif'),
  ('Saltos com Joelhos Altos', 'gifs/funcional-e-hit/saltos-com-joelhos-altos.gif'),
  ('Saltos de afastamento', 'gifs/funcional-e-hit/saltos-de-afastamento.gif'),
  ('Saltos em tesoura', 'gifs/funcional-e-hit/saltos-em-tesoura.gif'),
  ('Serrote', 'gifs/costas/serrote.gif'),
  ('Snap Jumps', 'gifs/funcional-e-hit/snap-jumps.gif'),
  ('Soco direto de direita', 'gifs/funcional-e-hit/soco-direto-de-direita.gif'),
  ('Socos', 'gifs/funcional-e-hit/socos.gif'),
  ('Step com elástico', 'gifs/funcional-e-hit/step-com-elastico.gif'),
  ('Stiff Unilateral com Barra', 'gifs/pernas/stiff-unilateral-com-barra.gif'),
  ('Stiff Unilateral com Halteres', 'gifs/pernas/stiff-unilateral-com-halteres.gif'),
  ('Stiff com Elástico de Resistência', 'gifs/funcional-e-hit/stiff-com-elastico-de-resistencia.gif'),
  ('Stiff com Halter', 'gifs/pernas/stiff-com-halter.gif'),
  ('Stiff com barra', 'gifs/pernas/peso-muerto-piernas-rigidas-con-barra.gif'),
  ('Subida na Corda sem Pernas', 'gifs/crossfit/subida-na-corda-sem-pernas.gif'),
  ('Subida no Step com Elevação de Joelhos', 'gifs/funcional-e-hit/subida-no-step-com-elevacao-de-joelhos.gif'),
  ('Superman', 'gifs/eretor-lombar/superman.gif'),
  ('Supino Alternado com Halteres', 'gifs/peitoral/supino-alternado-com-halteres.gif'),
  ('Supino Declinado Unilateral Pegada Martelo com Haltere', 'gifs/peitoral/supino-declinado-unilateral-pegada-martelo-com-haltere.gif'),
  ('Supino Declinado com Halteres', 'gifs/peitoral/supino-declinado-com-halteres.gif'),
  ('Supino Fechado', 'gifs/triceps/supino-fechado.gif'),
  ('Supino Inclinado com Halteres', 'gifs/peitoral/supino-inclinado-com-halteres.gif'),
  ('Supino Inclinado com Halteres e Pegada Invertida', 'gifs/peitoral/supino-inclinado-com-halteres-e-pegada-invertida.gif'),
  ('Supino Inclinado com Halteres em Martelo', 'gifs/peitoral/supino-inclinado-com-halteres-em-martelo.gif'),
  ('Supino Inclinado na Alavanca', 'gifs/peitoral/supino-inclinado-na-alavanca.gif'),
  ('Supino Inclinado na Máquina com Pegada Martelo', 'gifs/peitoral/supino-inclinado-na-maquina-com-pegada-martelo.gif'),
  ('Supino Invertido com Pegada Fechada', 'gifs/triceps/supino-invertido-com-pegada-fechada.gif'),
  ('Supino Reto', 'gifs/peitoral/supino-reto.gif'),
  ('Supino Reto na Máquina', 'gifs/peitoral/supino-reto-na-maquina.gif'),
  ('Supino Unilateral com Halteres com Pegada Reversa', 'gifs/peitoral/supino-unilateral-com-halteres-com-pegada-reversa.gif'),
  ('Supino Unilateral no Cabo', 'gifs/peitoral/supino-unilateral-no-cabo.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('Supino com Alavanca', 'gifs/peitoral/supino-com-alavanca.gif'),
  ('Supino com Halteres', 'gifs/peitoral/supino-com-halteres.gif'),
  ('Supino com Halteres Pegada Invertida', 'gifs/peitoral/supino-com-halteres-pegada-invertida.gif'),
  ('Supino com Pegada Fechada Sentado com Cabo', 'gifs/peitoral/supino-com-pegada-fechada-sentado-com-cabo.gif'),
  ('Supino com banco inclinado no Smith', 'gifs/peitoral/supino-com-banco-inclinado-no-smith.gif'),
  ('Supino com barra declinado', 'gifs/peitoral/supino-com-barra-declinado.gif'),
  ('Supino com barra no chão', 'gifs/peitoral/supino-com-barra-no-chao.gif'),
  ('Supino com cabo sentado', 'gifs/peitoral/supino-com-cabo-sentado.gif'),
  ('Supino com haltere pegada fechada', 'gifs/peitoral/supino-com-haltere-pegada-fechada.gif'),
  ('Supino com halteres com pegada fechada', 'gifs/peitoral/supino-com-halteres-com-pegada-fechada.gif'),
  ('Supino com kettlebell de um braço', 'gifs/peitoral/supino-com-kettlebell-de-um-braco.gif'),
  ('Supino com kettlebell no chão', 'gifs/peitoral/supino-com-kettlebell-no-chao.gif'),
  ('Supino com pegada aberta', 'gifs/peitoral/supino-com-pegada-aberta.gif'),
  ('Supino com pegada fechada', 'gifs/peitoral/supino-com-pegada-fechada.gif'),
  ('Supino declinada com alavanca', 'gifs/peitoral/supino-declinada-com-alavanca.gif'),
  ('Supino declinada na máquina', 'gifs/peitoral/supino-declinada-na-maquina.gif'),
  ('Supino declinado na máquina Smith', 'gifs/peitoral/supino-declinado-na-maquina-smith.gif'),
  ('Supino declinado pegada martelo', 'gifs/peitoral/supino-declinado-pegada-martelo.gif'),
  ('Supino em Pé com Faixa Elástica', 'gifs/funcional-e-hit/supino-em-pe-com-faixa-elastica.gif'),
  ('Supino inclinado com barra', 'gifs/peitoral/supino-inclinado-com-barra.gif'),
  ('Supino inclinado com cabo', 'gifs/peitoral/supino-inclinado-com-cabo.gif'),
  ('Supino inclinado com halteres e pegada fechada', 'gifs/peitoral/supino-inclinado-com-halteres-e-pegada-fechada.gif'),
  ('Supino inclinado com pegada fechada', 'gifs/peitoral/supino-inclinado-com-pegada-fechada.gif'),
  ('Supino inclinado na máquina', 'gifs/peitoral/supino-inclinado-na-maquina.gif'),
  ('Supino invertido com pegada aberta', 'gifs/peitoral/supino-invertido-com-pegada-aberta.gif'),
  ('Supino na Máquina para Miolo do Peitoral', 'gifs/peitoral/supino-na-maquina-para-miolo-do-peitoral.gif'),
  ('Supino na máquina', 'gifs/peitoral/supino-na-maquina.gif'),
  ('Supino na máquina Smith', 'gifs/peitoral/supino-na-maquina-smith.gif'),
  ('Supino no banco inclinado 30 graus com pegada invertida', 'gifs/peitoral/supino-no-banco-inclinado-30-graus-com-pegada-invertida.gif'),
  ('Supino no smith com o triângulo', 'gifs/peitoral/supino-no-smith-com-o-triangulo.gif'),
  ('Supino pegada martelo', 'gifs/peitoral/supino-pegada-martelo.gif'),
  ('Supino reto em pé no cross over', 'gifs/peitoral/supino-reto-em-pe-no-cross-over.gif'),
  ('Supino unilateral com Alavanca', 'gifs/peitoral/supino-unilateral-com-alavanca.gif'),
  ('Suspensão Passiva', 'gifs/calistenia/suspensao-passiva.gif'),
  ('Swimming', 'gifs/funcional-e-hit/swimming.gif'),
  ('Swing 360', 'gifs/calistenia/swing-360.gif'),
  ('Swing de kettlebell', 'gifs/crossfit/swing-de-kettlebell.gif'),
  ('Swing de kettlebell de um braço', 'gifs/crossfit/swing-de-kettlebell-de-um-braco.gif'),
  ('Tesoura de Braços', 'gifs/funcional-e-hit/tesoura-de-bracos.gif'),
  ('Toque Lateral dos Dedos dos Pés em Pé', 'gifs/mobilidade/toque-lateral-dos-dedos-dos-pes-em-pe.gif'),
  ('Toque nos Dedos dos Pés Sentado', 'gifs/mobilidade/toque-nos-dedos-dos-pes-sentado.gif'),
  ('Toque nos Dedos dos Pés em Pé', 'gifs/mobilidade/toque-nos-dedos-dos-pes-em-pe.gif'),
  ('Toques de Dedos em Pé', 'gifs/mobilidade/toques-de-dedos-em-pe.gif'),
  ('Torção Oblíqua Sentada', 'gifs/mobilidade/torcao-obliqua-sentada.gif'),
  ('Torções do Cotovelo para o Joelho', 'gifs/funcional-e-hit/torcoes-do-cotovelo-para-o-joelho.gif'),
  ('Tração lateral com elástico', 'gifs/funcional-e-hit/tracao-lateral-com-elastico.gif'),
  ('Tríceps Coice com Cabo', 'gifs/triceps/triceps-coice-com-cabo.gif'),
  ('Tríceps Coice com Halteres', 'gifs/triceps/triceps-coice-com-halteres.gif'),
  ('Tríceps Francês Alternada com Halteres no Banco Inclinado', 'gifs/triceps/triceps-frances-alternada-com-halteres-no-banco-inclinado.gif'),
  ('Tríceps Francês com Faixa Elástica Acima da Cabeça', 'gifs/funcional-e-hit/triceps-frances-com-faixa-elastica-acima-da-cabeca.gif'),
  ('Tríceps Francês com Halter Bilateral', 'gifs/triceps/triceps-frances-com-halter-bilateral.gif'),
  ('Tríceps Francês com Halteres', 'gifs/triceps/triceps-frances-com-halteres.gif'),
  ('Tríceps Francês em Pé com Gymstick', 'gifs/funcional-e-hit/triceps-frances-em-pe-com-gymstick.gif'),
  ('Tríceps Pulley barra V', 'gifs/triceps/triceps-pulley-barra-v.gif'),
  ('Tríceps Testa com Banco Declinado com Halteres', 'gifs/triceps/triceps-testa-com-banco-declinado-com-halteres.gif'),
  ('Tríceps Testa com Barra Pegada Invertida', 'gifs/triceps/triceps-testa-com-barra-pegada-invertida.gif'),
  ('Tríceps Testa com Faixa Elástica', 'gifs/funcional-e-hit/triceps-testa-com-faixa-elastica.gif'),
  ('Tríceps francês com barra W acima da cabeça sentado', 'gifs/triceps/triceps-frances-com-barra-w-acima-da-cabeca-sentado.gif'),
  ('Tríceps francês na polia com corda', 'gifs/triceps/triceps-frances-na-polia-com-corda.gif'),
  ('Tríceps francês no banco inclinado com halter', 'gifs/triceps/triceps-frances-no-banco-inclinado-com-halter.gif'),
  ('Tríceps francês unilateral no cabo', 'gifs/triceps/triceps-frances-unilateral-no-cabo.gif'),
  ('Tríceps no Banco', 'gifs/triceps/triceps-no-banco.gif'),
  ('Tríceps no Banco(1)', 'gifs/triceps/triceps-no-banco-1.gif'),
  ('Tríceps pulley barra', 'gifs/triceps/triceps-pulley-barra.gif'),
  ('Tríceps pulley corda', 'gifs/triceps/triceps-pulley-corda.gif'),
  ('Tríceps pulley pegada invertida', 'gifs/triceps/triceps-pulley-pegada-invertida.gif'),
  ('Tríceps testa com barra', 'gifs/triceps/triceps-testa-com-barra.gif'),
  ('Tríceps testa pegada neutra com halteres', 'gifs/triceps/triceps-testa-pegada-neutra-com-halteres.gif'),
  ('V-Up com Bola de Estabilidade', 'gifs/funcional-e-hit/v-up-com-bola-de-estabilidade.gif'),
  ('Virar Pneu', 'gifs/crossfit/virar-pneu.gif'),
  ('Voador com Halteres para Cima', 'gifs/peitoral/voador-com-halteres-para-cima.gif'),
  ('Voador de Deltoides Posterior com Cabo', 'gifs/trapezio/voador-de-deltoides-posterior-com-cabo.gif'),
  ('Voador invertido', 'gifs/ombros/voador-invertido.gif'),
  ('Voador na Máquina', 'gifs/peitoral/voador-na-maquina.gif'),
  ('Voador na Máquina para Deltoides Posteriores', 'gifs/trapezio/voador-na-maquina-para-deltoides-posteriores.gif'),
  ('Voador no pec deck', 'gifs/peitoral/voador-no-pec-deck.gif'),
  ('Voador para deltoides posterior com cabo', 'gifs/ombros/voador-para-deltoides-posterior-com-cabo.gif'),
  ('Voador unilateral no Solo com Barra', 'gifs/peitoral/voador-unilateral-no-solo-com-barra.gif'),
  ('Wall Sit', 'gifs/funcional-e-hit/wall-sit.gif'),
  ('Wall Sit com Inclinação de Tronco', 'gifs/funcional-e-hit/wall-sit-com-inclinacao-de-tronco.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);

INSERT INTO public.exercise_media (canonical_exercise_id, kind, object_key, mime_type)
SELECT e.id, 'gif', v.object_key, 'image/gif'
FROM (
  VALUES
  ('adução de pernas (alongamento do adutor maior)', 'gifs/mobilidade/aducao-de-pernas-alongamento-do-adutor-maior.gif'),
  ('elevação frontal com cabo duplo no cross', 'gifs/ombros/elevacao-frontal-com-cabo-duplo-no-cross.gif'),
  ('remada invertida com halteres inclinado', 'gifs/trapezio/remada-invertida-com-halteres-inclinado.gif')
) AS v(name_pt, object_key)
JOIN public.canonical_exercises e ON e.name_pt = v.name_pt
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_media m
  WHERE m.canonical_exercise_id = e.id AND m.kind = 'gif'
);
