import type { AdminUser } from "@/domain/admin/users";

export const PREVIEW_ADMIN_USER_TOTAL = 1247;

export const PREVIEW_ADMIN_USERS: AdminUser[] = [
  {
    id: "lucas",
    name: "Lucas Mendes",
    avatar: "/catalog/admin-users/lucas.webp",
    status: "Ativo",
    plan: "Elite",
    goal: "Hipertrofia",
    lastWorkout: "Peitoral e Tríceps",
    adherencePct: 84,
    lastActivity: "Hoje, 09:41",
  },
  {
    id: "amanda",
    name: "Amanda Santos",
    avatar: "/catalog/admin-users/amanda.webp",
    status: "Ativo",
    plan: "Pro",
    goal: "Definição",
    lastWorkout: "Quadríceps e Glúteos",
    adherencePct: 92,
    lastActivity: "Hoje, 08:30",
  },
  {
    id: "matheus",
    name: "Matheus Sales",
    avatar: "/catalog/admin-users/matheus.webp",
    status: "Ativo",
    plan: "Essencial",
    goal: "Hipertrofia",
    lastWorkout: "Costas e Bíceps",
    adherencePct: 68,
    lastActivity: "Ontem, 19:15",
  },
  {
    id: "carla",
    name: "Carla Oliveira",
    avatar: "/catalog/admin-users/carla.webp",
    status: "Inativo",
    plan: "Elite",
    goal: "Perda de Peso",
    lastWorkout: "Cardio HIIT",
    adherencePct: 48,
    lastActivity: "Há 5 dias",
  },
  {
    id: "ronaldo",
    name: "Ronaldo Silva",
    avatar: "/catalog/admin-users/ronaldo.webp",
    status: "Ativo",
    plan: "Pro",
    goal: "Condicionamento",
    lastWorkout: "Funcional Fullbody",
    adherencePct: 76,
    lastActivity: "Hoje, 10:15",
  },
  {
    id: "juliana",
    name: "Juliana Costa",
    avatar: "/catalog/admin-users/juliana.webp",
    status: "Ativo",
    plan: "Elite",
    goal: "Hipertrofia",
    lastWorkout: "Peito e Ombros",
    adherencePct: 89,
    lastActivity: "Hoje, 07:00",
  },
  {
    id: "fernando",
    name: "Fernando Souza",
    avatar: "/catalog/admin-users/fernando.webp",
    status: "Ativo",
    plan: "Essencial",
    goal: "Ganho de Força",
    lastWorkout: "Deadlift & Core",
    adherencePct: 94,
    lastActivity: "Ontem, 21:00",
  },
  {
    id: "patricia",
    name: "Patrícia Lima",
    avatar: "/catalog/admin-users/patricia.webp",
    status: "Inativo",
    plan: "Pro",
    goal: "Flexibilidade",
    lastWorkout: "Alongamento Avançado",
    adherencePct: 30,
    lastActivity: "Há 12 dias",
  },
  {
    id: "rodrigo",
    name: "Rodrigo Neves",
    avatar: "/catalog/admin-users/rodrigo.webp",
    status: "Ativo",
    plan: "Elite",
    goal: "Hipertrofia",
    lastWorkout: "Membros Superiores",
    adherencePct: 81,
    lastActivity: "Ontem, 18:45",
  },
  {
    id: "beatriz",
    name: "Beatriz Ramos",
    avatar: "/catalog/admin-users/beatriz.webp",
    status: "Ativo",
    plan: "Pro",
    goal: "Definição",
    lastWorkout: "Pernas & Abdômen",
    adherencePct: 88,
    lastActivity: "Hoje, 06:12",
  },
  {
    id: "gustavo",
    name: "Gustavo Pereira",
    avatar: "/catalog/admin-users/gustavo.webp",
    status: "Ativo",
    plan: "Essencial",
    goal: "Perda de Peso",
    lastWorkout: "Corrida Aeróbica",
    adherencePct: 72,
    lastActivity: "Ontem, 15:30",
  },
  {
    id: "helena",
    name: "Helena Vasconcelos",
    avatar: "/catalog/admin-users/helena.webp",
    status: "Ativo",
    plan: "Pro",
    goal: "Condicionamento",
    lastWorkout: "Pilates Solo",
    adherencePct: 85,
    lastActivity: "Ontem, 12:00",
  },
];
